### ISSUE TITLE
Need OpenID Connect Profile Endpoint

### ISSUE THREAD

**Issue by polastre** [18F/myusa#23]
OpenID connect specifies the claims that should be provided by OpenID providers.

The current `api/profile` endpoint provides our own format of each field.

We should either:
- Update `api/profile` to match OpenID Connect (note: this may break current clients)
- Create a new `api/profile/openid` that provides OpenID Connect formatted profile response (alternatively, provide `api/openid` or `api/profile-openid`

Full list of claims:
http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Note that we should add fields for:
- email verified
- phone verified

Obviously some of the claims do not apply to us at this stage (eg, picture).

**Comment by polastre** [comment]
@yozlet is working on an OpenID Connect profile for FICAM.  When it is available, @yozlet should add this to MyUSA via PR.

**Comment by yozlet** [comment]
No longer working on FICAM project, but OIDC may be the easiest way to get MyUSA integrated with RPs. However, we need to affirm this properly. Closing in favour or a research task.
