### ISSUE TITLE
Add Federated Analytics to all MyUSA pages

### ISSUE THREAD

**Issue by polastre** [18F/myusa#276]
We should be using the GSA Federated Analytics on production.

Putting in discovery because we need to:

- [ ] figure out the right federated analytics code to use
- [ ] create a new tracking id for the new MyUSA
- [ ] make sure our google accounts can access federated analytics
- [ ] register the code and test that it is working

@gbinal -- can you help us with this issue?

**Comment by jackiekazil** [comment]
#720 succeeds this ticket.
