### ISSUE TITLE
DevOps: Servers should have NewRelic for nginx installed

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#305]
Split from #275. This involves installing the [New Relic nginx plugin](http://newrelic.com/plugins/nginx-inc/13).

**Comment by cpapazian** [comment]
@yozlet @dlapiduz does our nginx configuration have the New Relic plugin configured?

**Comment by yozlet** [comment]
Not at the moment. I looked into it in the past and there was no decent Chef recipe for it, and it wasn't a high priority. Ideally this should go into the base image so it's available for other projects.

**Comment by yozlet** [comment]
No longer applies due to Cloud Foundry.
