### ISSUE TITLE
Page titles should be descriptive to the user

### ISSUE THREAD

**Issue by polastre** [18F/myusa#325]
Right now the title of every page says "MyUSA".  How can we have our views set the page title?

**Comment by polastre** [comment]
@kategarklavs can you propose titles for each of the MyUSA pages -- home, legal, profile, settings, notifications, etc.

**Comment by kategarklavs** [comment]
@polastre Sounds good. I'll touch base with the team for the timeline.

**Comment by cpapazian** [comment]
let's do the site map first. and then, if we decide it actually adds to the user experience, we can add page titles, but for now, the site is functional, and i'm not sure anybody actually cares about the titles.

**Comment by cpapazian** [comment]
let's block this on https://github.com/18F/myusa/issues/547

**Comment by polastre** [comment]
@cpapazian Google cares, and users use google. If you want to find, say, the MyUSA API docs or developer info, google wouldn't index the site correctly because every page appears to be the same page. 

The page titles have been a serious pet peeve of mine. All the tabs I have open for MyUSA all have the same text. I'd call that also a use case.

**Comment by cpapazian** [comment]
point taken. we're still going to block on #547. the sitemap is going to be a better context for coming up with titles, rather than just going one by one through the pages.

**Comment by kategarklavs** [comment]
@mkhandekar (and @esgoodman): Do you agree with @cpapazian's comment that working from the sitemap is the best way to go about renaming pages? Also: Is this issue still relevant? If so, I'm happy to create new page names + send them to the team. cc @jackiekazil

**Comment by esgoodman** [comment]
I think this is done. http://invis.io/A737JR2TD

**Comment by jackiekazil** [comment]
:+1:
