### ISSUE TITLE
Marketing messaging research for agencies

### ISSUE THREAD

**Issue by dutchashell** [18F/myusa#338]
Interview:
- [ ] Generate a basic script/ conversation guide to talk to agencies, focusing in on how we would like to be talking to agencies about MyUSA

Follow up with an email to interviewees with the home page and a brief Micro-Survey
Micro Survey: 
- [ ] Generate a micro-survey with 5 or fewer questions

**Comment by polastre** [comment]
Closing this out in favor of new `research` issues.
