### ISSUE TITLE
Users should be able to unsubscribe from email without logging in

### ISSUE THREAD

**Issue by polastre** [18F/myusa#357]
When a user receives an email notification (from a third party app), they should be able to click a link in the email to "unsubscribe" from those emails.

In reality, what we should do (for now) based on discussion with @dutchashell is implement "mute" and "unmute" for email delivery.  Apps can still send notifications (which could potentially be viewed through other methods), but the notifications will not be delivered to their email address if they turn the notification off.  They turn the notification off by unsubscribing.

A few notes:
- Notifications can only be sent to someone if they approved the `notifications` scope
- Unsubscribing does **not** change the approved scopes.  `notifications` are still approved as a scope.  All the user is doing is disabling the delivery of that notification by email.
- By thinking of this as a "mute" / "unmute" function, the user can turn on/off delivery by email through muting or unmuting.
- Consider that there may be multiple paths in the future that are muted/unmuted (eg, SMS vs email) 

A "notification settings management page" is the subject of another (yet to be posted but will be soon) issue.

**Comment by cpapazian** [comment]
@polastre should be done in https://github.com/18F/myusa/pull/426

**Comment by polastre** [comment]
I think there's a few things to test/confirm:

- Are there links in the emails to unsubscribe?
- Is there a landing page when you unsubscribe?
- What is the content on the landing page (can you help @kategarklavs)?  Something along the lines of "you've been unsubscribed.  manage your notification settings here" which takes you to a login page or the notification settings page (if you're logged in)

**Comment by kategarklavs** [comment]
@polastre Of course! I'll go through the unsubscription process, record my impressions, and get started on some content recommendations.

**Comment by cpapazian** [comment]
@polastre i have a test for this feature in https://github.com/18F/myusa/blob/devel/spec/features/notification_spec.rb. though, since we aren't really doing notifications in prod/stage, it's difficult to test.

**Comment by polastre** [comment]
@cpapazian will get @kategarklavs a screenshot so we can get some content.

**Comment by kategarklavs** [comment]
@polastre @cpapazian Aye aye! Chris, just let me know what your timeline is like, and I'll get the copy written.

**Comment by kategarklavs** [comment]
Here's some (friendly) replacement copy:

"Hey! You just hit unsubscribe — you’ll no longer get emails from <application name>.

You can always update your notification settings right here." 

("right here" = link)

CC @cpapazian

**Comment by kategarklavs** [comment]
Merged this pull request! Copy has been updated.
