### ISSUE TITLE
User should be able to turn on and force 2FA

### ISSUE THREAD

**Issue by polastre** [18F/myusa#398]
The user should have the option to enable two-factor authentication for all of their login activity.

Providing this would affect:
- Recovery messaging
- Login workflow
- Where the user can enable/disable 2FA (eg, settings, during onboarding, etc) -- feel free to break these out into new/separate stories.

**Comment by cpapazian** [comment]
https://github.com/18F/myusa/pull/455

**Comment by cpapazian** [comment]
should be all set once https://github.com/18F/myusa/pull/512 is merged

**Comment by polastre** [comment]
#512 merged; need to verify working as expected in order to accept.

**Comment by polastre** [comment]
Looks like there's a bug -- when I click enable 2FA I get this error on `alpha.my.usa.gov` trying to redirect to https://alpha.my.usa.gov/mobile_recovery/new

![screen shot 2015-01-29 at 1 53 01 pm](https://cloud.githubusercontent.com/assets/2539570/5967041/37d1576c-a7be-11e4-9550-eae28a2ff352.png)

**Comment by polastre** [comment]
Also reported by @amoose

**Comment by cpapazian** [comment]
hrmmm. works for me.

**Comment by polastre** [comment]
@cpapazian have you set up 2FA before turning this on?  I have not set up 2FA (clicked "skip this step") and then try to turn it on in the settings.  That's when I get the infinite page redirects.  Sounds like an edge case wasn't addressed.

ps: Now I can't even log in because I'm in a redirect loop.  UGH!

**Comment by cpapazian** [comment]
ah yes. that's bad.

**Comment by cpapazian** [comment]
this should working on stage now that https://github.com/18F/myusa/pull/543 has been merged

**Comment by jackiekazil** [comment]
Looks good to me.
