### ISSUE TITLE
Notification on/off buttons are confusing

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#435]
This is a common UI anti-pattern: the button represents both a state and an action, but it's not obvious which is which. If the button says "Off" does that mean I should click it to turn it Off, or is its current state already off?

If we want to keep this kind of state+action switch, better to make it the two-position slider used in iOS etc.

**Comment by esgoodman** [comment]
We are dealing with this in https://github.com/18F/myusa/issues/558

**Comment by mkhandekar** [comment]
We explored [on/off sates here](https://github.com/18F/myusa/issues/608#issuecomment-97157970) and have landed on a direction that fared well in usability research on the [permissions screen](https://github.com/18F/myusa/issues/739). 

**Permissions - all toggles off** 

![4_permissions_off](https://cloud.githubusercontent.com/assets/1598889/8995757/1a26866a-36d9-11e5-8255-8f736d55dcba.png)

**Permissions - one toggle on**

![4_permission_on](https://cloud.githubusercontent.com/assets/1598889/8995760/26e440a4-36d9-11e5-971d-208a48b57f5a.png)

**Comment by jackiekazil** [comment]
Yay!
