### ISSUE TITLE
Remove top right Connect with MyUSA button from the marketing home page

### ISSUE THREAD

**Issue by dutchashell** [18F/myusa#440]
This puts people in an awkward loop, let's get rid of that experience.

**Comment by polastre** [comment]
Iceboxing this for now because we may replace the main sign in box with content, which would mean the button is still necessary in the top right. This is dependent on #486.

**Comment by esgoodman** [comment]
Box removed per results of [front page evaluation](https://github.com/18F/myusa-ux/blob/master/research/front%20page%2020150222.md#-developers-want-more-information-before-signing-up)
