### ISSUE TITLE
add Refresh Token documentation to API docs.

### ISSUE THREAD

**Issue by cpapazian** [18F/myusa#441]

**Comment by cpapazian** [comment]
this is all set per #549 can somebody (@jackiekazil?) take a look on stage?

**Comment by jackiekazil** [comment]
@adelevie, I haven't had a chance to look this. Can you take a look, accept, and close? (unless more work is needed.)

**Comment by adelevie** [comment]
I don't understand the issue or problem space. @cpapazian or @yozlet, could one of you maybe write a sentence or two about where I can learn more about this.

**Comment by jackiekazil** [comment]
@adelevie -- these were just basic updates to the API documentation, where the documentation didn't exist before. See this pull request merge -- https://github.com/18F/myusa/pull/549/files 

(If you think more work should be done, close this and open a new ticket for that work.)

**Comment by jackiekazil** [comment]
I am going to go ahead and accept this. This looks like a fantastic update. :-)
