### ISSUE TITLE
User should be able to accept application's TOS when authenticating

### ISSUE THREAD

**Issue by polastre** [18F/myusa#445]
A user should be able to agree to an applications Terms of Service when authorizing the application.

This may be as simple as a link to the application's TOS and a line of text that says "By authorizing this application, you also agree to their Terms of Service"

Request from @ultrasaurus

**Comment by ultrasaurus** [comment]
It took a while to dig up this example of what facebook does:
![image](https://cloud.githubusercontent.com/assets/41906/5685937/c6eaf69a-97f3-11e4-9377-4334c8ad17ca.png)

**Comment by polastre** [comment]
First step is to figure out OGC's position on this and get a go ahead.

**Comment by ultrasaurus** [comment]
@polastre could you set up a meeting with OGC to discuss?  do we need anything in advance of that?

**Comment by polastre** [comment]
In progress...

**Comment by polastre** [comment]
OGC's response is :+1:, so long as we have a way to ensure that the links (TOS and Privacy Policy) are current.  That's a reasonable request -- Facebook actually fetches your link when you `blur` the TOS or Privacy Policy input when editing an application, checks that the page exists (HTTP 200), and displays an error if that's not the case.

**Comment by ultrasaurus** [comment]
That's wonderful!  THANK YOU!

So... what would it take to get this implemented?

**Comment by polastre** [comment]
We'll have to spec it out (likely later this week), then add it to a sprint (likely next sprint).

**Comment by polastre** [comment]
Specification that meets the legal requirements:

**Application Edit Page**
- Add a new text input field: Link to Application's Terms of Service (`tos_link`) (exact name is not important)
- Add a new text input field: Link to Application's Privacy Policy (`privacy_policy_link`)
- In the validation rules, check that each link exists if it is entered (HTTP 200)
- Allow blank inputs
- If `tos_link` has content, then `privacy_policy_link` *must* also have content

**Application Approval Page**

If both `tos_link` and `privacy_policy_link` are present, then:
- Above the line that says "You are authorizing MyUSA to...", include the new text "By proceeding, you agree to (Application Name's) Terms of Service and Privacy Policy."  This text should be set off from the text below it with a paragraph break.
- Terms of Service should be linked to `tos_link`
- Privacy Policy should be linked to `privacy_policy_link`

If `tos_link` or `privacy_policy_link` is empty or null, then the text "By proceeding..." should not be shown.

**Comment by cpapazian** [comment]
@ultrasaurus is this still a requirement for you guys? if so and if all we need to do is put the links in, then i can prioritize this.

**Comment by dhcole** [comment]
@cpapazian yea would love to have this in MyUSA if you think it makes sense. Otherwise, we need to build into Midas an additional step after authentication to present this message.

**Comment by cpapazian** [comment]
:+1:

**Comment by cpapazian** [comment]
can show TOS links on OAuth landing screen, but right now, when no scope is requested, we skip the OAuth landing screen (as per: https://github.com/18F/myusa/issues/229). @jackiekazil, please advise.

**Comment by adelevie** [comment]
Fixed by https://github.com/18F/myusa/pull/559.
