### ISSUE TITLE
Admin should say "Make Private" for Public apps

### ISSUE THREAD

**Issue by polastre** [18F/myusa#451]
If an app is already public, the option there should be to make it private (not public).

![screen shot 2014-11-12 at 4 19 35 pm](https://cloud.githubusercontent.com/assets/2539570/5021241/c8f0088e-6a87-11e4-9ee0-7bc4d3871ada.png)

**Comment by cpapazian** [comment]
should be all set once #465 is merged

**Comment by polastre** [comment]
Confirmed in #465.  Closing.
