### ISSUE TITLE
Admin should be able to see all apps

### ISSUE THREAD

**Issue by polastre** [18F/myusa#452]
As an Administrator, I should be able to see all apps in the system, regardless of whether they are public/private/pending.

Some possible solutions:
- Text filter (from @cpapazian)
- Bootstrap tabs based on stage (from @polastre)

Please propose a design, then do it!

**Comment by cpapazian** [comment]
should be all set once #465 is mergted

**Comment by polastre** [comment]
Confirmed in #465.  Closing.
