### ISSUE TITLE
Limit Profile to Geographical Information

### ISSUE THREAD

**Issue by polastre** [18F/myusa#467]
In the interest of shipping MyUSA to the public as soon as possible, limiting the amount of information we collect from people allows us to most expediently conduct user research without additional regulatory approvals.  In particular, according to the section "Items collected to create user accounts or profiles for agency websites." of [Social Media, Web-Based Interactive Technologies, and the Paperwork
Reduction Act](http://www.whitehouse.gov/sites/default/files/omb/assets/inforeg/SocialMediaGuidance_04072010.pdf), agencies can collect email address, phone number (for 2FA), and geographical information (state, region/country, and zip code) for the purpose of setting up user profiles.

The purpose of this issue is to reduce the MyUSA profile service _temporarily_ to collecting only those 5 items above.  Due to the potential for re-enabling these fields in the future, whatever implementation is proposed should have a relatively easy way of reverting back to the full profile once we have additional regulatory clearances.

In order to do this, I have specified the following changes:

- [x] Remove the "Profile" fields from the UI with the exception of state, country, and zip code.  Mobile number should be handled by the 2FA flow in Administration and not on the profile page (for now).
- [x] Remove the "Additional Information" profile page from the UI
- [x] Disable the `profile.*` OAuth scopes associated with the removed profile fields.  Still allow them to be specified as valid scopes by apps so as not to break existing apps.  But don't approve those scopes, and let the app query which scopes were approved using `/api/v1/tokeninfo`
- [x] Make sure the application authorization page only displays the valid profile scopes:
  - `profile.email` -- verified email address
  - ~~`profile.mobile_number` -- 2FA verified number~~
  - `profile.state`
  - `profile.country` -- if implemented
  - `profile.zip`
- [ ] Provide a mechanism to relatively painlessly revert these changes in the future

**Comment by cpapazian** [comment]
@polastre are we ready to add all these back in?

**Comment by polastre** [comment]
@cpapazian yes; closing this issue in favor of #515.

**Comment by polastre** [comment]
No longer a valid issue; we'll be reverting the work.  Marking `invalid`.
