### ISSUE TITLE
Revoking application results in 500 error

### ISSUE THREAD

**Issue by polastre** [18F/myusa#483]
When clicking "Revoke application" on myusa-staging.18f.us, you get a 500 (internal server error) error after you click "Ok" in the "Are you sure?" dialog.

**Comment by polastre** [comment]
@yozlet assigning to you to make sure the tokens have been nuked from prod.

**Comment by yozlet** [comment]
Does this still need doing? It's basically a `DELETE FROM oauth_access_grants;`, right?

**Comment by polastre** [comment]
@yozlet AFAIK, still needs to be done on prod.

**Comment by yozlet** [comment]
Done.

**Comment by yozlet** [comment]
Oops, not sure if mine was the last thing to do on this issue.

**Comment by polastre** [comment]
Yep, production was the last step.  Thanks @yozlet!
