### ISSUE TITLE
Front page needs to more accurately describe what MyUSA does (besides providing authentication)

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#485]
The current version of the MyUSA front page describes what MyUSA offers in terms of authentication, but doesn't provide as much information about other offerings (tasks, notifications, etc.)

Somewhat relatedly: The current front page mostly targets agencies, but also features copy targeted toward users. I'd like to standardize front page copy to target agencies.

To accomplish these goals, I'd like to draft and test new front page content. 

The test is in #486. Prior to testing, I need to achieve these tasks: 
- [x] Draft new content
- [x] Revise/iterate on content
- [x] Mock up B page @esgoodman will help with this

The new content should:
- Provide a more accurate picture of what MyUSA offers
- Differentiate MyUSA from Connect.gov
- Be targeted toward agencies

**Comment by kategarklavs** [comment]
New front page is mocked up and ready to go!

**Comment by polastre** [comment]
Is this content public somewhere?

**Comment by esgoodman** [comment]
see slack channel

On Mon, Jan 5, 2015 at 10:21 AM, Joe Polastre <notifications@github.com>
wrote:

> Is this content public somewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myusa/issues/485#issuecomment-68750987>.
>



-- 
Elizabeth Goodman
Innovation Specialist
18F / GSA
50 UN Plaza
San Francisco, CA 94103

**Comment by esgoodman** [comment]
# Front page mockup

![front page](https://cloud.githubusercontent.com/assets/10067318/5617614/6c464aa4-94c5-11e4-8440-f7f13e3acd0c.png)

original is editable in Sketch

**Comment by polastre** [comment]
:+1: thanks @esgoodman!
