### ISSUE TITLE
Create a template for surveys that we can reuse

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#487]
To achieve goals outlined in #486, I need to create a template that can be used to test distinct versions of pages within MyUSA.

Subtasks:

- [x] Create list of survey questions/general script (which can be modified for use in other surveys) – survey questions now available in Hackpad. 
- [x] Run by @esgoodman for feedback
- [x] Run by @cpapazian @polastre @yozlet for feedback 
- [x] Modify template as necessary

**Comment by polastre** [comment]
Is this template available somewhere?  Link to it?

Reopening to record where the work is done so we can look it up later if needed.

**Comment by kategarklavs** [comment]
Right now, I just have a (very) rough draft of a script/some survey questions – it's here: 

https://docs.google.com/a/gsa.gov/document/d/1NoWInFc_mCNa4w9vJ1EQ0JN1r2eDPwDw0LKRDAyAviY/edit?usp=sharing

My plan is to conduct hallway tests during which participants can mark up paper copies of the front page with new copy. I'll also be taking notes (either recording participants' comments on tape or typing notes – this isn't hammered out yet). The survey itself will be far less structured than the one I'd planned to send via email (with the intent of getting a more accurate and holistic view of how participants would interact with the front page).

**Comment by polastre** [comment]
@kategarklavs can we move this to GitHub wiki or Hackpad?  I get Google Docs for docs that are in process, but as various "releases" of the docs are ready, it would be good to share that with other teams and the public.

**Comment by polastre** [comment]
@kategarklavs which of the "todo" list items in the first bullet are completed?

**Comment by kategarklavs** [comment]
@polastre Yep, I can move this to Hackpad. The first bulletpoint (create survey) is complete, though the survey is in a different form than originally planned. Will transfer it to Hackpad now and request team feedback.

**Comment by polastre** [comment]
[Hackpad link for Onsite User Interview Questions / Hallway Tests (Template)](https://myusa.hackpad.com/Template-Onsite-User-Interview-Questions-hallway-tests-Sh0kBCZx9UI)

**Comment by polastre** [comment]
@kategarklavs is the first comment right about using surveymonkey?

**Comment by kategarklavs** [comment]
@polastre Alas, no – updated the description to reflect the current survey draft (which I copied/pasted into Hackpad)

**Comment by kategarklavs** [comment]
Hallway test questions are up on Hackpad: https://myusa.hackpad.com/Template-Onsite-User-Interview-Questions-hallway-tests-Sh0kBCZx9UI

@polastre @yozlet @cpapazian @esgoodman – I'd love your feedback! I'm planning to sit in the cafe next Monday or Tuesday (1/12 or 1/13) and start the testing process proper.

**Comment by esgoodman** [comment]
Are you done with this? If so, let's close it.

**Comment by kategarklavs** [comment]
@esgoodman Yes! Closing now.
