### ISSUE TITLE
Can users create an account? 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#490]
The first step in using MyUSA at all is creating an account. We need to mitigate any difficulties that keep users from successfully making new accounts. Subquestions include
- [ ] Where do users have trouble?
- [ ] What factors (e.g. content, interface elements) appear to be responsible?
- [ ] What changes are likely to mitigate the problems?

**Comment by esgoodman** [comment]
Answered specifically for federal employees in [research summary doc from walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#can-users-create-an-account-490)

**Comment by jackiekazil** [comment]
:+1:
