### ISSUE TITLE
Are users able to authorize and login to another MyUSA-enabled application if they already have an account?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#494]

**Comment by esgoodman** [comment]
Answered for federal employees by [the concept walkthrough in Jan/Feb](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#are-users-able-to-authorize-and-login-to-another-myusa-enabled-application-if-they-already-have-an-account-494).

**Comment by jackiekazil** [comment]
:+1:
