### ISSUE TITLE
Are government employees interested in using a single sign-on across government websites?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#497]
We need more data on what sorts of government employees might be interested in a single sign-on service, and how interested they are. 

We believe that there is some interest, but that the interest may vary depending on what sign-on services are currently available. 

This hypothesis to be tested with upcoming interviews, in which we'll walk participants through a demo of MyUSA's functionality.

**Comment by esgoodman** [comment]
Answered specifically for federal employees in [research summary doc from walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#are-government-employees-interested-in-using-a-single-sign-on-across-government-websites-497)

**Comment by jackiekazil** [comment]
:+1:
