### ISSUE TITLE
Do users believe that MyUSA handles their personal information appropriately?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#499]
MyUSA should not only meet users’ expectations for the respectful treatment personal information, but also effectively communicate to users how MyUSA respects their wishes. This issue is a hypothesis that we'll evaluate with interviews (Sprint 13) and hallway usability tests (later sprints). 

Questions to answer:
- [ ] How do potential users *want* MyUSA to store their personal information?
- [ ] How do potential users *expect* MyUSA to share their personal information? 
- [ ] What concerns do they have about how other shared sign-on services work?

**Comment by esgoodman** [comment]
UPDATE: This would need more research with general public (as opposed to gov employees). It is answered for gov employee purposes in the [conceptual frameworks presentation](https://docs.google.com/a/gsa.gov/presentation/d/1Qa1xQDwjLq88TxSYUf7KTngO4IMsHo1dLmV2pxWJc40/edit?usp=sharing), slide 23. I'd like to add a bit more detail though.

**Comment by esgoodman** [comment]
Answered more specifically in [research summary doc from walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#do-users-believe-that-myusa-handles-their-personal-information-appropriately-499)

**Comment by jackiekazil** [comment]
:+1:
