### ISSUE TITLE
No New Relic data for production

### ISSUE THREAD

**Issue by polastre** [18F/myusa#502]
There's only new relic data for staging -- why not production (myusa.18f.us)?

/cc @dlapiduz and @yozlet

**Comment by yozlet** [comment]
Turns out it's not working in either staging or production.

Closing this in favour of #503.

**Comment by polastre** [comment]
@yozlet this is a different issue than #503.  #503 is about errors.  This is about just raw servers reporting in.

**Comment by yozlet** [comment]
Production data now coming in (thanks to new config deployment)

**Comment by polastre** [comment]
Data present in staging and production.  Accepting.
