### ISSUE TITLE
Errors are not being reported to New Relic

### ISSUE THREAD

**Issue by polastre** [18F/myusa#503]
When a 500 error occurs, such as #483, the error is not propagated to New Relic. New Relic shows no errors for the last 7 days, yet I know I've caused a bunch of 500 errors reproducing #483 (and the logs show this).

Need to enable error reporting in New Relic.

/cc @dlapiduz and @yozlet

**Comment by yozlet** [comment]
Both staging and production are seeing the same issues in the logs. First, it reports an invalid license key at startup:
```
[01/05/15 20:07:37 +0000 ip-10-0-1-178 (6369)] ERROR : Invalid license key: b14104f4cbf99aeb59ef99bf6a0c2986b6369b83
```

... but I've triple-checked this license, and it's identical to the one that NR's console says is ours.

Then, we get failed attempts every 10 mins:
```
[01/05/15 20:13:50 +0000 ip-10-0-1-178 (6369)] ERROR : Error establishing connection with New Relic Service at collector.newrelic.com:443:
[01/05/15 20:13:50 +0000 ip-10-0-1-178 (6369)] ERROR : NewRelic::Agent::ServerConnectionException: Unexpected response from server (400): Unknown Version
[01/05/15 20:13:50 +0000 ip-10-0-1-178 (6369)] INFO : Will re-attempt in 60 seconds
```

I've been doing a bunch of Googling and reading yet found nothing. However, it does look like our NR gem is quite old, so I'm going to try upgrading that.

**Comment by yozlet** [comment]
Application data now coming in for both staging and production.

**Comment by yozlet** [comment]
Note: I see no errors there yet, but I think that's just because we haven't generated any. Can you contradict that?

**Comment by polastre** [comment]
We need a way to generate an error on each of staging and production.  @cpapazian any suggestions?

**Comment by polastre** [comment]
Ah, we can generate an exception with #520 merged.  So let's merge and deploy that and we can kill two birds with one stone.

**Comment by polastre** [comment]
Errors are being reported!  Yay.  Filed #535 for additional error logging that we should have.
