### ISSUE TITLE
Prepare data from comparative concept testing for analysis

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#506]
Raw interview data is in the form of video and handwritten notes. To make it usable by the team, relevant quotes and observations need to be 
- [ ] extracted from video/notes
   - [x] P01
   - [x] P02
   - [ ] P03
- [ ] turned into manipulatable items like post-its or plaintext

**Comment by polastre** [comment]
This is an ongoing activity that we'll be updating documents, so no need for an issue.
