### ISSUE TITLE
Derive findings from comparative concept testing 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#507]
Once we've transformed the raw fieldwork data into media we can all work with, we need to draw out larger themes. This is going to be an on-going activity across multiple sprints until we decide to stop doing comparative concept testing and close related issues such as #497, #61, #55. As we do more interviews, we'll use the data to draw out new themes and test whether our old themes are still useful and well-grounded.

**Comment by polastre** [comment]
This is part and parcel of doing concept testing and interviews, and will be covered in each of the issues around themes or questions that we're trying to answer.
