### ISSUE TITLE
Update production to new domain and get email working

### ISSUE THREAD

**Issue by polastre** [18F/myusa#509]
`alpha.my.usa.gov` is up and running.  But a few things are left to be done:
- [x] update the production.rb config to use the correct hostname
- [x] get email from @[hostname] (@alpha.my.usa.gov) tested and working

/cc @yozlet and @dlapiduz

**Comment by yozlet** [comment]
Plan:
1. Update CFN template to choose SSL cert based on the hostname parameter
2. Update active hostname parameter in the live stack settings
3. Normally we'd gradually terminate/create instances, but that's risky at the moment, so the remaining option is to go in and edit manually.

**Comment by yozlet** [comment]
All done and working and lovely, yay.

**Comment by polastre** [comment]
This should be smoke tested by someone on the team in order to accept.

**Comment by polastre** [comment]
working!
