### ISSUE TITLE
API Docs: Confirm that developers need to select at least one scope for their app

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#514]
Just asked @cpapazian whether developers need to select at least one scope for their app, or whether they can decline this decision – Chris determined that apps require at least 1 scope.

@polastre: Can you confirm that this is the case?

**Comment by cpapazian** [comment]
@polastre i confirmed that this is the case. wondering if it _should_ be the case. might make sense to set up an app without profile/notifications/tasks to just handle auth. do we want to allow no scopes? or possibly create another scope for just oauth?

**Comment by kategarklavs** [comment]
@cpapazian Thank you for clarifying(!)

**Comment by polastre** [comment]
We _should_ allow no scopes for apps that purely want to use MyUSA as a token provider for each user that accesses their services.

**Comment by cpapazian** [comment]
sounds good. should be an easy fix.

**Comment by polastre** [comment]
@cpapazian I don't think there's any work to be done here.

@kategarklavs what exactly is this issue proposing?  Currently developers don't need to select _any_ scopes, and I think we should keep it this way to allow applications that just need an anonymous token to track sessions.

**Comment by cpapazian** [comment]
@polastre, i asked @kategarklavs to create this issue. she was asking about some documentation, and when i tested this, it seemed to require at least one scope. if we do not want that functionality, we should create an issue to fix it. make sense?

**Comment by polastre** [comment]
Ah yes, thank you @cpapazian

**Comment by kategarklavs** [comment]
@polastre As @cpapazian mentioned, this was just regarding the API docs I'm working on – I wasn't sure whether any scopes were required. Happy to provide more info (and apologies for the confusion)!

**Comment by polastre** [comment]
We should make a decision: **is at least one scope required?**

If **yes**, then the API docs just need to reflect his.
If  **no**, then the code should be updated _and_ API docs updated to reflect.

**Comment by kategarklavs** [comment]
Whatever you all decide, just keep me posted and I'll update the API doc accordingly.

**Comment by polastre** [comment]
Doorkeeper has the concept of default scopes which we can use to implement a `null` scope.  @cpapazian to propose a dev fix for this, then we need to update the API docs.

**Comment by cpapazian** [comment]
will need to update the API docs to reflect changes to support this.

**Comment by cpapazian** [comment]
investigating how to set up default scope/allow for no scope.

**Comment by cpapazian** [comment]
while looking in to whether we can easily change things so that applications are not required to request scopes (answer is we can), i noticed that we skip the authorization screen when no scopes are requested. here's the change: https://github.com/18F/myusa/commit/0dfd38da02403186344c7fc71c93056f7824d5f3 ... do we actually want this? the app isn't requesting any data, but it still seems like we may want the user to explicitly approve the client application ...

**Comment by polastre** [comment]
@cpapazian discussed *ad nauseum* with the results in https://github.com/18F/myusa/issues/229#issuecomment-54191928

**Comment by cpapazian** [comment]
thanks, @polastre

**Comment by cpapazian** [comment]
closing in favor of https://github.com/18F/myusa/issues/552
