### ISSUE TITLE
What perceptions do people have about the governmental use of commercial identity providers?

### ISSUE THREAD

**Issue by polastre** [18F/myusa#52]
Questions to test:  Are there any indicators that users will decide to _not_ use social account logins to access MyUSA?  Are users willing to use certain services with government (MyUSA) more than others?

This may be done through market research, surveys, prototypes, paper prototypes, or a combination of both in order to test conscious and unconscious response.

**Comment by esgoodman** [comment]
Title edited to make the question more specific.

**Comment by esgoodman** [comment]
Answered for federal employees by [concept walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#reactions-to-federated-identity-schemes)

**Comment by jackiekazil** [comment]
Looks good to me!
