### ISSUE TITLE
How do government employees react to signing in with companies that are associated with a specific business function (such as Verizon or Paypal)?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#522]
Pilot interviews suggest that government employees see a difference between signing into government websites through providers associated with social interactions (e.g. Facebook, Google, Twitter) and signing into government websites through services associated with specific business functions (e.g. Paypal, Verizon). This question investigates that hypothesis.

**Comment by polastre** [comment]
@esgoodman can you provide a summary of the answer and what action items resulted from your research on this question?

**Comment by esgoodman** [comment]
Helps us answer #52.

**Comment by polastre** [comment]
@esgoodman if you point us to the research summary we can close this out

**Comment by esgoodman** [comment]
UPDATE: Just need to deal with making publicly visible research summary. It is answered for our purposes in the [conceptual frameworks presentation](https://docs.google.com/a/gsa.gov/presentation/d/1Qa1xQDwjLq88TxSYUf7KTngO4IMsHo1dLmV2pxWJc40/edit?usp=sharing), slide 23

**Comment by esgoodman** [comment]
Answered more specifically [in concept testing summary](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#how-do-government-employees-react-to-signing-in-with-companies-that-are-associated-with-a-specific-business-function-such-as-verizon-or-paypal-522)

**Comment by jackiekazil** [comment]
:+1:
