### ISSUE TITLE
How do we effectively explain how MyUSA works to non-technical users?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#524]
Users need to know how MyUSA works to derive the most benefit from it.

**Comment by kategarklavs** [comment]
+1 to this (and this is an issue I'm happy to work on, as well).

**Comment by esgoodman** [comment]
FOR CONTEXT: This is a broader research question which I anticipated answering gradually, over time. I am still working out how best to document those evolving understandings in a way that's easy for me, accessible to the team, and visible to the public.

**Comment by esgoodman** [comment]
More information (https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md)[here].

**Comment by jackiekazil** [comment]
@esgoodman to update! :-)

**Comment by esgoodman** [comment]
Moved to UX repo: https://github.com/18F/myusa-ux/issues/12.
