### ISSUE TITLE
Can participants use the permissions screen to control which types of data a new application can access?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#528]
We have a working version of a permissions screen, but it hasn't gotten much testing. We need to test whether people can use the current permissions page to control which types of data a new application may use. The question is not whether users are choosing to restrict data sharing, but whether they can do so if they want. 

We're first testing this with #505, then will move to live deployments when we have them.

**Comment by polastre** [comment]
We may need prototypes to effectively test this, so blocked on design/prototype implementation.  Needs a few designs to test.

**Comment by esgoodman** [comment]
UPDATE: Somewhat addressed by #505. Results need to be documented. Will post a link when I do. Because #505 used a demo clickthrough rather than a live version, however, I'd take the results with a bit of salt.

**Comment by esgoodman** [comment]
Answered by concept evaluation and [Midas integration testing in Sprint 22](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-results.md). The answer is "no" and we are testing solutions to the problem in [Sprint 25](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint25_hallway-SFFB.md)

**Comment by jackiekazil** [comment]
:+1:
