### ISSUE TITLE
How do users respond to auth mechanisms that don't use passwords?

### ISSUE THREAD

**Issue by polastre** [18F/myusa#53]
Question: If MyUSA uses other authentication mechanisms from passwords (eg, emails, SMS, etc), do users notice the difference in logging in and (if they notice) what is their reaction?

**Comment by esgoodman** [comment]
Answered for pre-re-inception version of MyUSA by [walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#how-do-users-respond-to-auth-mechanisms-that-dont-use-passwords).

**Comment by jackiekazil** [comment]
Yup!
