### ISSUE TITLE
Make click-through demo showing MyUSA deployment on publicly accessible apps 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#530]
Since a number of MyUSA's partners are making services for the general public, we should have a click-through demo (likely Invision) illustrating those integrations. Then we can show that click through to current users of publicly accessible websites and get their reactions. 

The current plan is to use healthcare.gov and usajobs.gov because they are already highly visible and people's motivations for visiting them shouldn't need much extra explanation. The Sketch screens we made for showing to federal employees will be the template.

**Comment by esgoodman** [comment]
More detail on the scenarios and use cases being examined with this file are [here](https://myusa.hackpad.com/SxnkP0yQBcT).

**Comment by esgoodman** [comment]
UPDATE: Done but having trouble uploading it to InVision, so I don't want to close the issue.

**Comment by jackiekazil** [comment]
This is resolved! YAY!
