### ISSUE TITLE
As a developer, I can't seem to be able to delete an application

### ISSUE THREAD

**Issue by ultrasaurus** [18F/myusa#532]
When I click "Delete My Application"
I see "Are you sure?" popup,
I see a blank page
![image](https://cloud.githubusercontent.com/assets/41906/5928355/72b826b6-a62f-11e4-85fc-a3fa16078fe7.png)

which appears to be a 404 error:
![image](https://cloud.githubusercontent.com/assets/41906/5928371/927040ec-a62f-11e4-8d10-fafd23b07e29.png)

If I go back, my app is still there

**Comment by cpapazian** [comment]
this is working for me. @ultrasaurus, let me know if this is still broken for you, and i can dig in to replicate.

**Comment by cpapazian** [comment]
this works!

**Comment by ultrasaurus** [comment]
Thanks!
