### ISSUE TITLE
utf encoding is not set correctly for alpha.my.usa.gov

### ISSUE THREAD

**Issue by cpapazian** [18F/myusa#536]
@yozlet the string encodings for the alpha myusa database doesn't seem to be set ... 

`ActiveRecord::StatementInvalid: Incorrect string value: '\xE2\x9C\x93","...' for column 'data' at row 1`

**Comment by cpapazian** [comment]
@yozlet this is still broken on alpha.my.usa.gov. can you please take a look? thanks!

**Comment by cpapazian** [comment]
this is preventing @ultrasaurus and @dhcole from testing with myusa on midas-dev

**Comment by yozlet** [comment]
Fixed by running this on the DB:
```sql
ALTER TABLE myusa.authentication_tokens CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.authentication_tokens CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.authentications CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.authentications CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.authorizations CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.authorizations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.feedbacks CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.feedbacks CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.notifications CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.notifications CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.oauth_access_grants CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.oauth_access_grants CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.oauth_access_tokens CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.oauth_access_tokens CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.oauth_applications CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.oauth_applications CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.oauth_scopes CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.oauth_scopes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.profiles CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.profiles CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.roles CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.roles CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.roles_users CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.roles_users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.schema_migrations CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.schema_migrations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.sms_codes CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.sms_codes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.task_items CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.task_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.tasks CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.tasks CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.unsubscribe_tokens CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.unsubscribe_tokens CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.user_actions CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.user_actions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
ALTER TABLE myusa.users CHARACTER SET utf8 COLLATE utf8_unicode_ci;   ALTER TABLE myusa.users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;  
```

... but this is not a good permanent solution. We need something in the schema file or similar.

**Comment by yozlet** [comment]
... except that didn't set all the column encoding/collations too. UGH.
The problem in this case was `authentications.data`, a TEXT column. I've changed the encoding there, but we need a new schema.

**Comment by cpapazian** [comment]
let's also make the change that will prevent this from reoccurring before accepting.

**Comment by yozlet** [comment]
OK, I seem to have fixed the error - it's working now. I did a DB export, changed all the `latin1` columns to `utf8` and imported again. But no, this isn't a permanent solution.

**Comment by yozlet** [comment]
Permanent solution involves:
 - [ ] adding DB parameter group to RDS
 - [ ] changing CFN template to use new DB parameter group
 - [ ] testing

**Comment by yozlet** [comment]
Added to the CFN template: https://github.com/18F/cloud-cutter/commit/756a882cb223d8b5116735a4484a347cc7ab903c

Note: This also involved the creation of a `DBParameterGroup` called `utf8`, available to all RDS MySQL instances in us-east-1. (Short version: it's a basic Parameter Group for MySQL 5.6 with all but one of the `character_set_` parameters set to `utf8`, `character_set_filesystem` set to `binary` and the `collation` params set to `utf8_unicode_ci`)

**Comment by cpapazian** [comment]
sweet! @yozlet, i would like to spin up a new myusa instance (maybe on cloud foundry?) to do some testing of the saml integration. we can use this deploy to test this new setting and then accept the task. can we pair on this tomorrow some time?

**Comment by yozlet** [comment]
Gaah, didn't see this at the time, sorry! Very up for pairing on this either tomorrow or when I get back, if you still want to.

**Comment by cpapazian** [comment]
:+1:

**Comment by jackiekazil** [comment]
Were you guys able to connect on this?

**Comment by cpapazian** [comment]
we still haven't had the chance to spin up the new environment to test these changes. once we can do that, i'll accept the story.

**Comment by adelevie** [comment]
tested with a brand new stack, confirmed everything is utf8
