### ISSUE TITLE
SMS phone number doesn't show up on production

### ISSUE THREAD

**Issue by polastre** [18F/myusa#537]
It should say "Enter the code delivered to (number)".  But the (number) is missing!

/cc @yozlet and @cpapazian!

![screen shot 2015-01-29 at 3 01 49 pm](https://cloud.githubusercontent.com/assets/2539570/5968195/d4c0d7e0-a7c9-11e4-8e30-16c1a1ae1090.png)

**Comment by cpapazian** [comment]
https://github.com/18F/myusa/pull/545

**Comment by cpapazian** [comment]
updated #545 per @yozlet's suggestion. Need to merge that so we can accept this.

**Comment by cpapazian** [comment]
done in https://github.com/18F/myusa/pull/545

**Comment by jackiekazil** [comment]
Done and accept.
