### ISSUE TITLE
Developers need clearer documentation for tasks and checklists

### ISSUE THREAD

**Issue by polastre** [18F/myusa#540]
If you expand the `PUT` response in the current API docs, you can see all of the attributes.  Sadly the docs claim that things only have a `name` field which is not true, nor does it describe the difference between a task container and a task checklist item.  See https://alpha.my.usa.gov/developer#task-

Here's my notes on how Tasks actually work:

> A "task" consists of a series of "task items" (the checklist).  So the app creates a new "task" which it names something like "Apply for Social Security".  The task items are then the checklist -- "Get Form 32" and "Notarize form 32" and "Send to SSA".  The task items have two attributes -- `name` (a string that describes the task) and optionally `url` (a link to do the item if it is an online activity).
>
> I should point out the obvious as well -- each "task item" has a `completed` timestamp which tells you whether that item has been completed (checked off) and when.
>
> Apps can set the `completed` attribute via the API, so _either_ the user can mark something as done _or_ the app can mark it complete behind the scenes using the API.

We need to fix the following things:

- [ ] Explain the difference between a `task` (container) and a `task_item` (checklist entry)
- [ ] Explain how to create, update, an delete a `task` (with `task_items`)
- [ ] Explain how to create, update, an delete a `task_item` (inside an existing `task`)
- [ ] Define all of the `task` and `task_item` attributes that you can set (eg, `name`, `url`, `completed`, etc)
- [ ] Update the **Request** and **Response** json objects in the API docs to match the new info

**Comment by polastre** [comment]
@kategarklavs will likely need to work with @cpapazian to dig into the actual code (models and controllers) to extract the useful info and update the documentation.

**Comment by kategarklavs** [comment]
@polastre I'll schedule some time with @cpapazian so we can work together on this!

**Comment by kategarklavs** [comment]
@cpapazian Here's a link to the API documentation copy I've worked on with @yozlet:

https://docs.google.com/a/gsa.gov/document/d/17fySpW30no_tUkAqOGTEIdBNQTRvR3KM6qgwdzm_dyI/edit?usp=sharing

Let me know what sorts of copy changes you'd like moving forward.

**Comment by kategarklavs** [comment]
@cpapazian and I met yesterday (2/4/15) to discuss the current state of the API docs + necessity of writing/rewriting task-related content. We agreed that content writing can proceed once a visual design is developed.

**Comment by polastre** [comment]
Peanut gallery comment: why does there need to be a visual design to write API documention for developers?

**Comment by cpapazian** [comment]
@kategarklavs i think we still need to fix up the API docs for tasks, but i can take a crack at it while i'm doing this other stuff.

**Comment by kategarklavs** [comment]
@cpapazian Sounds good! Once all the basic info is laid out, let me know & I'll work on tone, phrasing, etc.

**Comment by kategarklavs** [comment]
Incidentally, just committed changes to Getting_started.md (doc improvements branch).

**Comment by kategarklavs** [comment]
@adelevie and @yozlet — Two questions for you!

1) What's the status of the API docs for tasks (mentioned in early February by @cpapazian); and
2) Does the documentation need to be updated? 

I'd previously made copy changes to the existing documentation; if you all feel it needs further revisions, let me know!

**Comment by kategarklavs** [comment]
Just talked to @esgoodman — we're happy to close this, for now (no one has expressed issues w/current documentation).
