### ISSUE TITLE
Rollover is distractingly jumpy for the top three text links on the home page

### ISSUE THREAD

**Issue by ericronne** [18F/myusa#544]
On hover:
 - Keep typeface unchanged (currently changes to bold)
 - Change font color to #117cb2
 - Increase thickness of the underscore bar to 4 pixels
 - Change underscore bar color to #117cb2

![image](https://cloud.githubusercontent.com/assets/9259185/6049561/444ea58e-ac7e-11e4-9d84-c42fea803350.png)

**Comment by esgoodman** [comment]
Is this resolved by https://github.com/18F/myusa/issues/576?

**Comment by mkhandekar** [comment]
We are changing the top nav, so closing this issue.
