### ISSUE TITLE
Make site map

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#547]
We need a sitemap to resolve https://github.com/18F/myusa/issues/325 and to inventory our screen design needs before prioritizing them. I can't find a proper sitemap in any of the Drive folders. Let's make one.

- [x] Get a list of current pages from developers
- [x] Translate to graphic form

Updated to do list (1/2):

- [x] clean up [mural.ly] (https://mural.ly/t/gsa6/m/gsa6/1424375506222), gather insights
- [x] site map round 1 - option 1 (with most consensus around data structure)
- [x] site map round 1 - option 2 (with outliers)
- [x] focus on global navigation & how a user gets to all content from there
- [x] schedule meeting to review
- [x] site map review meeting
- [x] site map round 2
- [x] go through [benefits.gov] (http://www.benefits.gov/benefits/benefit-finder) and [business usa] (http://business.usa.gov/access-financing) sign up process as an experiment 
- [x] review round 2 with team

**Comment by kategarklavs** [comment]
@esgoodman — @cpapazian and I are meeting tomorrow to go through all the pages. I'll compile a list (Drive) and share it with the team. (It won't be pretty, but it will, fingers crossed, be complete.)

**Comment by esgoodman** [comment]
That's a great start. Thanks. Can you stick the list in the Design folder?

On Mon, Feb 9, 2015 at 5:08 PM, Kate Garklavs <notifications@github.com>
wrote:

> @esgoodman <https://github.com/esgoodman> — @cpapazian
> <https://github.com/cpapazian> and I are meeting tomorrow to go through
> all the pages. I'll compile a list (Drive) and share it with the team. (It
> won't be pretty, but it will, fingers crossed, be complete.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myusa/issues/547#issuecomment-73625403>.
>



-- 
Elizabeth Goodman
Innovation Specialist
18F / GSA
50 UN Plaza
San Francisco, CA 94103

**Comment by jackiekazil** [comment]
@mkhandekar, I was chatting w/ @esgoodman -- can you connect w/ her about this? I *believe* you are working on this already in some way yes? So, I am going to assign this to you.

**Comment by mkhandekar** [comment]
I am! @esgoodman can you point me to "Get a list of current pages from developers" on Drive that you mentioned earlier in this thread?

**Comment by kategarklavs** [comment]
@mkhandekar There is no list (at least, not to my knowledge). @cpapazian and I met a few weeks back to start work on this, but decided list generation should go along with the rest of the sitemap work.

**Comment by mkhandekar** [comment]
For [Sprint 20] (https://docs.google.com/a/gsa.gov/document/d/1d99NgoYAnxNSoE2fnHIYNMdIaP31jGeOEy9u8HczdL0/edit):

- [ ] clean up mural.ly, gather insights
- [ ] site map round 1 (2 options: one where there was most consensus, and another including outliers)
- [ ] focus on global navigation & how a user gets to all content from there
- [ ] schedule meeting to review
- [ ] site map review meeting
- [ ] site map round 2
- [ ] go through [benefits.gov] (http://www.benefits.gov/benefits/benefit-finder) and [business usa] (http://business.usa.gov/access-financing) sign up process as an experiment

**Comment by mkhandekar** [comment]
Goals: articulate 1) the user flow from front page to the rest of myusa, 2) log in & log out paths from myusa and agency websites, 3) an understanding of major content on each page

Site map (on Invision) — [top level nav](https://projects.invisionapp.com/d/main#/console/2318574/67600015/comments) & [dashboard](https://projects.invisionapp.com/d/main#/console/2318574/67600016/comments)
* Feedback & content suggestions are within comments on Invision.

![myusa_sitemap_toplevel_login](https://cloud.githubusercontent.com/assets/1598889/6666246/e3f7a262-cbb8-11e4-8f41-61c5f43f0821.png)
![myusa_sitemap_dashboard](https://cloud.githubusercontent.com/assets/1598889/6666245/e3f66212-cbb8-11e4-8c2d-9e4f4b385f82.png)

**Comment by cpapazian** [comment]
@mkhandekar, a couple things that don't look quite right ... 

- The 'from agency' flows do not originate from the 'landing page'. This isn't clear from the graphs, as they seem to be part of the flow that starts with the landing page in the top left.
- The case where the flow starts 'from agency', but the user is already logged in is missing. This is an important use case, even though the interaction with MyUSA is minimal.
- 'Check email' is listed as a step only in the 'new user' flows. The emailed token is an alternate login method and not necessarily part of the new user experience. That is, if the user uses Google's OAuth service, they won't receive an email with a link to click (whether or not it is their first time). However, if a user does not want to use Google, they can use the passwordless email token method, which is available for new and returning users.
- The SMS/2FA configuration that is part of the new user flow is missing. This is actually the only thing that differs between the new and returning user flows.
- It is not clear that the user authorizes MyUSA *only* on the first time they log in with an agency website.

**Comment by cpapazian** [comment]
Q: What happens when you log in via agency site

Short answer: The user should be taken back to the agency site. 

Long answer: The redirect to the profile when the user logs in from the front page is a special case. Since the user is unlikely to actually be interested in the front page, we decided redirected to the profile made sense. The more likely scenario is that the user is redirected to the log in flow b/c they are trying to access a restricted page. This could be an OAuth authorization screen if they were directed to MyUSA from an agency site or the dashboard if they are trying to administer the MyUSA configuration settings for an agency site. In these cases, the user should be redirected back to where they were. They would not be redirected directly to the agency site, rather, they would be redirected back to the OAuth authorization page, which would either prompt the user to authorize MyUSA or, if they had already done that, redirect the user (the second redirect) back to the agency site.

**Comment by esgoodman** [comment]
@cpapazian Can you specify where the SMS/2FA flow should start? I just sent you an email with a link to the correct page in Invision to annotate.

**Comment by cpapazian** [comment]
not sure how to use invision, but the 2fa/sms setup starts after login has completed. so, at the point which a returning user would be redirected back, a new user is prompted to configure their sms/2fa. after which, they would be redirected back. 

if you want to test drive this, you can create as many myusa accounts as you want by using the email+token flow. google allows you to append any characters to an email address by including a '+'. For example, if you email 'elizabeth.goodman+testing@gsa.gov' it will resolve to the same address as 'elizabeth.goodman@gsa.gov'.

**Comment by esgoodman** [comment]
We'll give it a shot. Thanks for the "+" tip.

**Comment by mkhandekar** [comment]
Here are the updated flows. They should address all of the points from the feedback, except SMS/2FA flow (to come in the next day).

**Top Level**
![myusa_sitemap_toplevel_login](https://cloud.githubusercontent.com/assets/1598889/6784044/99fdf1fc-d13a-11e4-8189-f0dad594c2b9.png)
**Account / Dashboard**
![myusa_sitemap_dashboard](https://cloud.githubusercontent.com/assets/1598889/6784043/99fd4df6-d13a-11e4-8017-8872adc80a34.png)

**Comment by esgoodman** [comment]
Done for now. https://projects.invisionapp.com/d/main#/console/2318574/82558829/preview

**Comment by jackiekazil** [comment]
:+1:

**Comment by jackiekazil** [comment]
I just want to say that this work makes me so happy. It is well done. :-)
