### ISSUE TITLE
Are users willing to provide additional info during application authorization?

### ISSUE THREAD

**Issue by polastre** [18F/myusa#55]
If MyUSA gives users the ability to provide additional information (that previously has not been provided) when they are authorizing an application, will they provide it?

**Comment by esgoodman** [comment]
Answered for pre-re-inception version of MyUSA by [walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#are-users-willing-to-provide-additional-info-during-application-authorization-55).

**Comment by jackiekazil** [comment]
Yup yup
