### ISSUE TITLE
Enable file uploading to MyUSA repo

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#550]
It would be really helpful for research documentation to be able to host screenshots _within_ our repo for easy insertion into Gists (which don't currently support direct file uploading). @onezerojeremy tells me that the Peace Corps project uses this app (see screenshot):

![screen shot 2015-02-18 at 2 59 42 pm](https://cloud.githubusercontent.com/assets/10067318/6273483/9413122e-b824-11e4-859f-6288a39d8c17.png)

I have no opinions myself on whether Heroku is the way to go but Gist's limitations in terms of uploading binaries is blocking/slowing public documentation of research findings.

**Comment by seanherron** [comment]
Yeah! We enabled this very easily - you can simply change the URL (eg https://github-uploader.herokuapp.com/18f/myusa) and it will work for the myusa repo.

**Comment by cpapazian** [comment]
thanks!

**Comment by esgoodman** [comment]
@jackiekazil what folder should research documentation images go into?

**Comment by jackiekazil** [comment]
@cpapazian Isn't everything in this repo app related? 
(assuming that is true)
@esgoodman how do you feel about a separate repo for the images, so they end up getting deployed with code?

**Comment by esgoodman** [comment]
I'm fine with whatever you guys think makes most sense. My vote would be a
separate repo for research and design work, though. I just met a designer
who's very happy with that solution at his company.

On Fri, Feb 20, 2015 at 8:25 AM, Jackie Kazil <notifications@github.com>
wrote:

> @cpapazian <https://github.com/cpapazian> Isn't everything in this repo
> app related?
> (assuming that is true)
> @esgoodman <https://github.com/esgoodman> how do you feel about a
> separate repo for the images, so they end up getting deployed with code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myusa/issues/550#issuecomment-75266613>.
>



-- 
Elizabeth Goodman
Innovation Specialist
18F / GSA
50 UN Plaza
San Francisco, CA 94103

**Comment by jackiekazil** [comment]
@esgoodman Let's do a new repo --- feel free to set one up as it makes sense to you -- don't over think it, we can reorg as needed. :)

**Comment by esgoodman** [comment]
The new repo is https://github.com/18F/myusa-ux. Upload images to using https://github-uploader.herokuapp.com/18f/myusa-ux.
