### ISSUE TITLE
BusinessUSA is an experiencing an error with integration testing

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#551]
`Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) (Mysql2::Error)`
Is this related to #536?

(Assigning this to @cpapazian, @yozlet -- if you could take it that would be great -- reassign to yourself.)

**Comment by cpapazian** [comment]
this looks like the "old" myusa, which neither i nor @yozlet have access to. @jackiekazil, do you know which environment they should be testing on? if we need to get the old one back up, i believe @jgrevich is the only one with the keys. can we get them set up on the new environment?

**Comment by cpapazian** [comment]
@jackiekazil, passing this back to you, as this is out of my hands.

**Comment by jackiekazil** [comment]
:+1:

**Comment by jackiekazil** [comment]
Closing this ticket. This is has been resolved.
