### ISSUE TITLE
Application owner should be able to generate a new key pair

### ISSUE THREAD

**Issue by cpapazian** [18F/myusa#555]
@ultrasaurus is reporting that the key regeneration just displays the old key. We should generate a new key when user asks for key to be regenerated.

**Comment by ultrasaurus** [comment]
actually it seems to display the old public key and a new secret key.

**Comment by cpapazian** [comment]
not actually a key-pair. just 2 unique id's. makes sense that we keep the public client id.

**Comment by ultrasaurus** [comment]
confirmed.  Not a bug.
