### ISSUE TITLE
Translate whiteboard sketches into clearer explanatory diagrams

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#556]
We have a bunch of sketches from conversations in the SF office. They need to be redrawn, clarified, and annotated so we can use them in discussions outside the team.

**Comment by esgoodman** [comment]
Internal docs available in [Drive](https://docs.google.com/a/gsa.gov/presentation/d/1VP55GChf-FnCh9w9m8V9L0hOTKPFtrRFmFm-UuwxiTg/edit?usp=sharing). Liz will refine as needed, on the assumption that they will be made public in a blog post.

**Comment by jackiekazil** [comment]
Looks good to me.
