### ISSUE TITLE
MVP Design

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#558]
After [wireframes] (https://github.com/18F/myusa/issues/557) are done, design global navigation and major interaction elements:

- [x] typography
- [x] global navigation > #729 Header & Footer states
- [x] switches
- [ ] dropdowns
- [ ] lists
- [x] iconography / illustrations

**Comment by esgoodman** [comment]
Also see: https://github.com/18F/myusa/issues/478

**Comment by mkhandekar** [comment]
Closing this issue in favor of related issues:

#576: Landing page content & design revamp ([in development here](https://github.com/18F/myusa/issues/723))
#729: Header & Footer states
#735: Sign in flow — to code
#711: Account Management
