### ISSUE TITLE
Document that mysql needs to be UTC

### ISSUE THREAD

**Issue by adelevie** [18F/myusa#560]

**Comment by adelevie** [comment]
via @cpapazian: http://stackoverflow.com/questions/947299/how-do-i-make-mysqls-now-and-curdate-functions-use-utc

**Comment by adelevie** [comment]
To do this on OSX with brew-installed mysql:


find the `my.cnf` file:
```
mysql --help
```

Something like this will be in the long help dialogue:

```
Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf /usr/local/etc/my.cnf ~/.my.cnf 
```

Open `/etc/my.cnf` (it was blank for me and required sudo to save), and add:

```
[mysqld_safe]
timezone = UTC
```

Restart mysql:

```
mysql.server restart
```

**Comment by yozlet** [comment]
@cpapazian updated the docs here: https://github.com/18F/myusa/blob/devel/INSTALL.md
