### ISSUE TITLE
Summarize existing research on authentication and authorization user experience 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#561]
There's a bunch of existing industry, government and academic research on the usability and public perception of OAuth and other identity frameworks. Much of it is very relevant to our efforts and should inform decision-making internally and with our partners. Hence, we are making a summary! 

Up for discussion as to format and eventual storage location.

**Comment by esgoodman** [comment]
In progress [here] (https://docs.google.com/a/gsa.gov/presentation/d/1mFsR-wsZqdJSy6UJf9sP0u8rFdwVbV2szcxsiXnPCPM/edit?usp=sharing)

**Comment by esgoodman** [comment]
Now basically [done] (https://docs.google.com/a/gsa.gov/presentation/d/1mFsR-wsZqdJSy6UJf9sP0u8rFdwVbV2szcxsiXnPCPM/edit?usp=sharing)

**Comment by jackiekazil** [comment]
Looks good!
