### ISSUE TITLE
Usability study of account management website

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#562]
As we get closer to live integrations, we need to revise the account management pages. For the next sprint, we will get started on comparing:

1) existing pages (using integration with Midas)
2) new [wireframes](https://github.com/18F/myusa/issues/557)

using conversations with internal clients and friends-and-family

**Comment by esgoodman** [comment]
Research plan is [here](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-plan.md)

**Comment by esgoodman** [comment]
Research results are [here](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-results.md)

**Comment by jackiekazil** [comment]
:+1:
