### ISSUE TITLE
Resolve with partner sites how LOA1 providers show up in sign in flow

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#564]
@ultrasaurus points out that we see LOA1 providers show up in the Midas-specific sign in screen (LinkedIn) and in the MyUSA-provided screen (Google). This seems odd to Sarah. Reporting this as a question to resolve now so that we can transfer the lessons to other clients.  

![midas](https://cloud.githubusercontent.com/assets/10067318/6565545/04dccc14-c66e-11e4-9b45-ecbb21797a63.png)

**Comment by esgoodman** [comment]
@ultrasaurus reports 

1. that a number of Open Opps users are using the "connect with Google" option. 
2. that we need to preserve the name/password sign-in option on this screen.

**Comment by esgoodman** [comment]
After much [discussion](https://github.com/18F/myusa-ux/issues/4), it seems clear that at least for the moment MyUSA should keep supporting the status quo. @mkhandekar's [current mock](http://invis.io/SJ301PF5U) for this screen has external IdPs separated from MyUSA. 

I think a good resolution for this issue will involve returning to the basic features of this screen

![sign in window screenshot with giant Google button in the middle](https://cloud.githubusercontent.com/assets/10067318/7241263/7e5cc232-e76c-11e4-9f3e-fd6657bf92a4.png)
 
but redesigning it so that the sign-in with Google button is not the first and only thing users see.

**Comment by jackiekazil** [comment]
This will discussed further during this sprint.

**Comment by mkhandekar** [comment]
Some integrators, such as Open Opportunties and Communicart, need their visitors to be able to sign in with Google. These integrators will have to explicitly request Google as a sign in option. Then Google will appear as the default sign in method. 

**See #738 (Sign in flow — sign in from Integrator website using Google) for the full flow**, and key screens are below.

===

##### 2.3 Connect With Google (by default)
![2 3_connectwithgoogle_default](https://cloud.githubusercontent.com/assets/1598889/8961063/b36207b6-35d8-11e5-9918-3f652040eec1.png)
A [Connect with Google] button and a text link that allows visitors to [sign in with any email] that takes them to the following screen.


##### 2.2 Sign in with email (secondary choice)
![2 2_signinemail_secondary](https://cloud.githubusercontent.com/assets/1598889/8961070/bd6b0b4a-35d8-11e5-9952-80c412cf6063.png)
A place for visitors to sign in with any email and a text link that allows them to [Connect with Google] that takes them to the previous screen.
