### ISSUE TITLE
Use HTTPS for confirmation link in email

### ISSUE THREAD

**Issue by adelevie** [18F/myusa#573]

**Comment by konklone** [comment]
Ah, I filed a dupe ticket in #650. It ended up being more detailed, though.

**Comment by yozlet** [comment]
Grabbing this one because it's easy to fix while doing the Cloud Foundry work (since `production.rb` is getting overhauled, and that's where the fix happens)

Answer: http://stackoverflow.com/questions/9459892/how-to-define-a-host-with-https-in-action-mailer-default-url-options

**Comment by NoahKunin** [comment]
Just confirming this a must fix, hostile networks are very real.

**Comment by harrisj** [comment]
This should be fixed in 8fc9a1d8333f58490d47da887b1f685cd0ca665d. A related issue was Mandrill was rewriting all email links to do clickthrough tracking and that has also been disabled.

**Comment by jackiekazil** [comment]
As soon as #650 is accepted and closed, we can close this ticket.

**Comment by jackiekazil** [comment]
And we can close this one also! YAY!

**Comment by konklone** [comment]
Thanks for nailing these, y'all!
