### ISSUE TITLE
Landing page content & design revamp

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#576]
Goal: 1) address user testing feedback, 2) resolve content & hierarchy issues on landing page

[Landing page (version 1 with user testing notes, on Invision)](https://projects.invisionapp.com/d/main#/console/2318574/62062701/comments)
* @esgoodman & @kategarklavs did user testing on this version
* Feedback & content suggestions are within comments on Invision.

![front page](https://cloud.githubusercontent.com/assets/1598889/6661157/c172c0ae-cb7d-11e4-8ddf-ea63c360e960.jpg)

**Comment by mkhandekar** [comment]
[Landing page (version 2, on Invision)](https://projects.invisionapp.com/d/main#/console/2318574/67015221/comments)
* Major changes include 
  * content for the most part re-written. see Kate's work re: [content evaluation summary](https://docs.google.com/a/gsa.gov/spreadsheets/d/1wJCj1pL0M92JajSM0tIKYEDCLkkynEEqJS56p-oWERQ/edit#gid=0)
  * a more streamlined top navigation
  * clearer link colors & call to actions in the hero area
  * icons for the 3rd section with the hope that they illustrate the steps better
* Feedback & content suggestions are within comments on Invision.

![landing5](https://cloud.githubusercontent.com/assets/1598889/6661160/dab14a2c-cb7d-11e4-9967-1e9b4c13776e.png)

**Comment by mkhandekar** [comment]
[Landing page (version 3, on Invision)](https://projects.invisionapp.com/d/main#/console/2318574/67854726/comments)
* Minor changes include 
  * adjustment to alignment of elements in the top nav and 2nd section
  * simpler content and design for the 3rd section
  * additional clarity in copy
* Feedback & content suggestions are within comments on Invision.

![150312_landing](https://cloud.githubusercontent.com/assets/1598889/6661161/de288d64-cb7d-11e4-936d-3b9cdde8f571.png)

**Comment by mkhandekar** [comment]
Programming has started on this design: #580.

**Comment by juliaelman** [comment]
Fixed with #580.
