### ISSUE TITLE
Reconcile Trello/Huboard/Github

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#578]
Reconcile Trello/Huboard/Github -- get us on one. 
Redo Github tags to match Trello tags, so that folks feel cool using Huboard instead of Trello, so tickets are processed in on place.

**Comment by esgoodman** [comment]
I think what's keeping me using Trello is an easy way to separate (logically and visually) "in progress" tasks from the next highest priority tasks in the backlog.  Our current Github labelling practices don't really allow for that.

**Comment by jackiekazil** [comment]
:+1:

**Comment by polastre** [comment]
Peanut Gallery: check out waffle.io.

**Comment by mkhandekar** [comment]
As a first step to combining github + trello/some other service we take 1/2 hour this week and:
- clean up labels so they play well with an interface like trello
- only have things in the sprint that we are working on 
I started to do this today, but don't want to mis-label things I don't have background knowledge about.

**Comment by polastre** [comment]
@mkhandekar context on **all** the labels in existence as of 6 weeks ago: https://github.com/18f/myusa/wiki/Agile

**Comment by jackiekazil** [comment]
Closing this. There seems to be no further action to take at this time.
