### ISSUE TITLE
Redirect loop issue on alpha

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#579]
Today while demoing myusa I was using the midas dev instance to show an application interacting with MyUSA. MyUSA the redirect loop issue happened multiple times in different places. It was weird, because I kept getting pointed to "https://alpha.my.usa.gov/mobile_recovery/new" .... even though that is not the link that I clicked on. This happened when logging in. it also happened when I clicked on "profile"
This happened at the following times... 
* When logging in w/ an account. 
* On the https://alpha.my.usa.gov/authorizations page 
 * Clicking on Personal, Additional, My Applications, Notifications, Account Settings. 

This didn't happen all at once, but now it is happening everywhere. 
Now I can't log in. 

@mkhandekar has had the same issue.

**Comment by yozlet** [comment]
I get the same issue on staging. Looking at the logs, we have tons of these before the browser gives up:
```
I, [2015-03-17T20:58:30.762612 #14558]  INFO -- : Processing by MobileRecoveriesController#new as HTML
I, [2015-03-17T20:58:30.765851 #14558]  INFO -- : Completed 401 Unauthorized in 3ms
I, [2015-03-17T20:58:30.853313 #14555]  INFO -- : Started GET "/mobile_recovery/new" for 159.142.71.4 at 2015-03-1
```

The problem, in a nutshell:
* MyUSA won't log this user into an authenticated session until they've set up 2FA
* MyUSA won't show the 2FA setup page until they've got an authenticated session

The `401 Unauthorized` is caught by Rails, which turns that into a 302 to the authentication page, which makes the browser re-fetch the page, etc.

**Comment by esgoodman** [comment]
I didn't have this problem with midas-dev today with both a new account and an old one.

**Comment by adelevie** [comment]
### Hypothesis

A piece of our code conflates the mere presence of a number in the database and the user's preference to require 2FA.

Look at the filter:

```ruby
class SettingsController < ApplicationController
  # ...
  before_filter :require_two_factor!, if: :two_factor_configured?
```

`if_two_factor_configured?` is defined in the `application_controller.rb`:

```ruby
def two_factor_configured?
  current_user.mobile_number.present?
end
```

### Proposal

Redefine `two_factor_configured?` to:

```ruby
def two_factor_configured?
  current_user.mobile_number.present? && user.two_factor_required
end
```

I did this and ran tests locally and got the following errors:

```
Failures:

  1) Two Factor Authentication user has enabled two-factor user can require two-factor
     Failure/Error: sms_page.token.set code
     Capybara::ElementNotFound:
       Unable to find css "#sms_raw_token"
     # ./spec/features/two_factor_spec.rb:75:in `block (3 levels) in <top (required)>'

  2) Account Settings visiting account settings page two-factor is configured two-factor authentication is required
     Failure/Error: expect(sms_page).to be_displayed
       expected `#<TwoFactor::SmsPage:0x007fae713031b8>.displayed?` to return true, got false
     # ./spec/features/settings/account_settings_spec.rb:28:in `block (4 levels) in <top (required)>'
```

Source for failure 1:

```ruby
  context 'user has enabled two-factor' do
    def code; receive_code; end
    let(:user) { FactoryGirl.create(:user, two_factor_required: false, mobile_number: phone_number) }
    before :each do
      account_settings_page.load
      sms_page.token.set code
      sms_page.submit.click
    end

    it 'user can require two-factor' do
      expect(account_settings_page.two_factor).to have_two_factor_required_checkbox
    end
  end
```

Source for failure 2:

```ruby
  describe 'visiting account settings page' do
    before :each do
      login(user)
      account_settings_page.load
    end

    context 'two factor is not configured' do
      let(:user) { FactoryGirl.create(:user) }

      it 'can access settings page' do
        expect(account_settings_page).to be_displayed
      end
    end

    context 'two-factor is configured' do
      let(:user) { FactoryGirl.create(:user, :with_2fa) }

      it 'two-factor authentication is required' do
        expect(sms_page).to be_displayed
      end
    end
  end
```

**Comment by yozlet** [comment]
Both of these test failures are the same issue, just showing up in different ways: they're going to the account settings page and expecting to see the SMS form, but they're actually seeing something different, because now `two_factor_configured?` is returning `false` where it was previously returning `true`.

**Comment by adelevie** [comment]
Hypothesis: to recreate locally, have user object with:

- two_factor_required: true
- mobile_number: nil

maybe:
- unconfirmed_mobile_number: 123-567-7890

h/t @yozlet

**Comment by yozlet** [comment]
Confirmed: This happened to users who had `two_factor_required` set but no confirmed `mobile_number`. (This should no longer be possible through Rails: https://github.com/18F/myusa/pull/543 )

Short term fix was to clean up those records on staging and production, because there were very few. Long term fix is, probably, to tweak `warden` to allow the user through to the mobile number setup page, similar to what the admin interface does.

**Comment by yozlet** [comment]
Added long term fix as #584, because I'm not convinced we need it yet.

**Comment by jackiekazil** [comment]
Is this ticket ready for accept?

**Comment by adelevie** [comment]
Yes? The fix here was a manual database update, with no code or PR.

**Comment by jackiekazil** [comment]
:+1:
