### ISSUE TITLE
Tasks API

### ISSUE THREAD

**Issue by mbalasanyan** [18F/myusa#585]
I am having trouble with the tasks API (/api/tasks).    A POST request to that endpoint to create a new MyUSA task appears to be successful and returns the newly created task with the ID.  I, however, cannot see any tasks in my MyUSA profile. Subsequent GET requests to that endpoint also come back empty. 

All of this is on http://myusa-staging.18f.us.

**Comment by adelevie** [comment]
Thanks for filing, @mbalasanyan. I will look into this.

**Comment by adelevie** [comment]
Solved.
