### ISSUE TITLE
Review/edit welcome test on myusa-support email group

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#589]
@kategarklavs : I just sent an invite to the support list to you (& others on myusa team) .... can you review the test in the support group welcome page to make sure that is good? Let me know if there are changes that should be made.

Text:

-----
WELCOME! We are so happy to have you here as a part of the MyUSA-Support group!

The purpose of this group is...  
... for folks integrating MyUSA to be able to communicate directly with each other.
... get updates on MyUSA.
... ask questions about MyUSA.
If you have an issue that needs to be addressed or if a discussion turns into an action item, please submit a ticket to the [github repo](https://github.com/18F/myusa/issues).

**Comment by adelevie** [comment]
I think it's fine. Maybe capitalize GitHub, but not a big deal either way.

**Comment by jackiekazil** [comment]
@adelevie Github is now capitalized.

**Comment by adelevie** [comment]
Now I can sleep at night!

**Comment by kategarklavs** [comment]
Just made a few small changes — I think this should be ready to go :)


WELCOME! We are so happy to have you here as part of the MyUSA-Support group!
The purpose of this group is ...

... to let folks who are integrating MyUSA communicate directly with each other.
... to share updates on MyUSA.
... to offer a space where you can ask questions about MyUSA.

If you have an issue that needs to be addressed or if a discussion turns into an action item, please submit a ticket to our GitHub repo.

**Comment by kategarklavs** [comment]
@jackiekazil Are you OK with closing this issue?

**Comment by jackiekazil** [comment]
Updated! https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/myusa-support
