### ISSUE TITLE
Display the API key for apps

### ISSUE THREAD

**Issue by afeld** [18F/myusa#591]
I have had the issue where I have app credentials on my machine, but lose track of which MyUSA app they came from. I understand that the API secret is sensitive and is thus only shown immediately after creation, but the API key shouldn't need to be hidden.

**Comment by adelevie** [comment]
@afeld, see https://github.com/18F/myusa/issues/389.

Mind if I close this issue and have all discussion take place in #389?

**Comment by afeld** [comment]
:+1: Got lazy about searching for existing issues for this one!

**Comment by adelevie** [comment]
great minds make the same mistakes :) https://github.com/18F/myusa/issues/577
