### ISSUE TITLE
Switch from SES to Mandrill for email delivery

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#593]
MyUSA is, by its nature, going to generate a lot of email bounces. Mandrill appears to be considerably more tolerant of this than SES.

**Comment by yozlet** [comment]
This needs:
* Switch to using [Mandrill's SMTP server](http://help.mandrill.com/categories/20090941-SMTP-Integration)
* Rename AWS SES credentials to Mandrill in MyUSA Server
* Rename credentials in MyUSA Cookbook
* Encrypt & upload Mandrill secrets

**Comment by jackiekazil** [comment]
@yozlet -- if @adelevie hasn't started looking into this, can you make this your #1 priority?

**Comment by yozlet** [comment]
@jackiekazil: Yep, am on it.

**Comment by yozlet** [comment]
All done! Cookbook PR is https://github.com/18F/myusa-cookbook/pull/7

**Comment by jackiekazil** [comment]
refs #654
