### ISSUE TITLE
Evaluate initial experience with small business owners

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#596]
It looks like MyUSA has a number of potential integrators who serve small business owners. We haven't done any research with small business owners, nor have we done much research with potential users who are not on the coasts. This study will focus on small business owners across the US, aiming for 6-9 participants (most likely remote, but potentially some in-person). 

Locations are tbd. We will be looking for maximum variety in region and business type, but trying to focus on sole proprietors of new businesses, since we are informed that these make up the majority of US small businesses. 

- [x] Write intro paragraph
- [x] Make recruitment plan
- [x] Write script
- [x] Recruiting
- [x] Doing interviews 
- [x] Analysis 

See evolving research plan [here](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint23_small-business.md)

**Comment by mkhandekar** [comment]
Here's the message that we can send out:

—

Our team at 18F is working to improve sign-in and account management for government websites. One of our main goals right now is to streamline the interactions of small business owners and employees with the federal government.

To do that, we are currently interviewing small business owners and employees about how they use government websites for their work. We want to hear your ideas for improving the sign on and account management process and share our own.

Each interview will take about an hour. If you are located within two hours’ drive of San Francisco, we will talk in person. If you are located farther away, we will talk on the phone. Either way, interviews will take place at a time and date that works for you. We can also schedule interviews in two phases if that helps in finding time.

To schedule an interview, ask questions about the project, or tell us about your login experiences, email Elizabeth Goodman at elizabeth.goodman@gsa.gov.

If you don’t have the time right now but might be interested in the future, please email us anyway! We have many projects and we are always looking for people to talk to.

**With your help, we can make accessing government information and resources easier for everyone.**

**Comment by esgoodman** [comment]
Note that it's not only small business owners but also employees...

**Comment by esgoodman** [comment]
[Script here](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint33_small-business-script.md). Feel free to comment on the last commit.

**Comment by esgoodman** [comment]
[Analyzing data in mural.ly](http://mur.al/bJ0qBg9D). Please ask me for the edit link or offer comments below.

**Comment by jackiekazil** [comment]
@esgoodman to update and close.

**Comment by esgoodman** [comment]
[Read the report](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint33_small-business-results.md)
