### ISSUE TITLE
MyUSA: An Overview for Non-Technical Folks

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#598]
The MyUSA team talked about the need for a blog post re: MyUSA for non-technical audiences.

Post would be explanatory (i.e., what is MyUSA and why would one use it?), relatively short (approx 500 words) and targeted at a non-technical audience.

**Comment by kategarklavs** [comment]
To-dos:

- [ ] write initial draft of post
- [ ] share with team for feedback
- [ ] iterate on post
- [ ] meet with @melodykramer and @esgoodman to discuss personas in the post
- [ ] add personas to the post
- [ ] final feedback from team
- [ ] submit to comms for approval
- [ ] publish!

**Comment by kategarklavs** [comment]
**Update**: Post is blocked until we get ATO.

**Comment by kategarklavs** [comment]
Added persona section (w/two personas) to the post + posted link in Slack channel. Will make any changes the team requests, then send the post on for review.

**Comment by kategarklavs** [comment]
Incorporated Liz's comments on personas (thank you, @esgoodman!) and submitted to Ori for comms review.

Will comment once post receives comms approval, and from there we can determine a pub date.

**Comment by jackiekazil** [comment]
Unblocked... we are moving forward to use this as a way to get people excited!

**Comment by kategarklavs** [comment]
Post was published on 5/18: https://18f.gsa.gov/2015/05/18/myusa/

Closing the issue.
