### ISSUE TITLE
Code up learn more page 

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#601]
Code up learn more page front end code, per @mkhandekar design specs. This pull request should be submitted against `feature/redesign` branch.

**Comment by mkhandekar** [comment]
Version 1:

![myusa - about - for agencies](https://cloud.githubusercontent.com/assets/1598889/7120400/fa8b5c7a-e1da-11e4-8b39-e694c6b8a267.png)
![myusa - about - for visitors](https://cloud.githubusercontent.com/assets/1598889/7120401/fa8bce62-e1da-11e4-96fd-fb31f50d3756.png)

I'm not where I'd like these pages to be. More work to be done on them by this Wednesday end of day (15-04-15), including: 
- [ ] Alternate, more dynamic layout for each sub section
- [ ] Icons 

cc: @jackiekazil @juliaelman

**Comment by juliaelman** [comment]
@mkhandekar right on and thanks for posting these! Do you think that the layout could possibly change drastically from this? If not, I might just go ahead and start working on building this out (as we talked about before).

**Comment by jackiekazil** [comment]
Update: a couple more research updates from Liz. Then Meghana will make adjustments as needed, then it is ready to code.

**Comment by juliaelman** [comment]
After speaking with both @mkhandekar and @esgoodman, this issue is no longer relevant in the current iteration of this homepage.
