### ISSUE TITLE
Find small business owners/employees to interview

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#604]
We are looking for 
- small business owners or employees 
- who don't live in places where we have already done a lot of testing (e.g. not on the coasts)

in order to complete research in https://github.com/18F/myusa/issues/596. 

(Turning recruitment into its own issue because the task is taking longer than expected.)

**Comment by esgoodman** [comment]
Now getting referrals to people in Chicago and Dayton.

**Comment by esgoodman** [comment]
This is taking a lot longer than I'd planned.

**Comment by esgoodman** [comment]
With help from @jackiekazil now going to use MyUSA's FB and Twitter accounts to talk to existing users (as per conversation with @quepol about rules for doing so).

- [ ] write tweet
- [ ] write FB post

**Comment by esgoodman** [comment]
- [ ] post messages

**Comment by esgoodman** [comment]
Working on Orlando, FL.

**Comment by esgoodman** [comment]
Now with participation from Tucson folks!

**Comment by jackiekazil** [comment]
@kategarklavs can you post or were we holding off for #628

**Comment by kategarklavs** [comment]
I believe we were waiting for #628 — now that it's done, I'll post a notice to small business owners!

**Comment by kategarklavs** [comment]
@jackiekazil Done!

**Comment by jackiekazil** [comment]
:+1: :us:

**Comment by esgoodman** [comment]
Progress update: 2/3 done.

**Comment by esgoodman** [comment]
Deprioritized for now. Will re-open if and when it becomes part of a team push.
