### ISSUE TITLE
Microcopy for Sign-In Flow

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#607]
Content focus for this week is generating microcopy for the sign-in flow. Members of the team identified this need in part because of the required use of Tock for time tracking — being that we're now expected to use Tock (which we log into using MyUSA), we found that a user's progress through the flow isn't as clear as it could be.

I'll create microcopy to guide users through the flow and will work with @mkhandekar and @esgoodman to integrate said copy into the design. 

- [x] first draft of microcopy changes
- [x] distribute to team for feedback
- [x] incorporate feedback
- [x] collaborate with @mkhandekar and @adelevie to create design & development timelines

**Comment by kategarklavs** [comment]
Sent V1 of copy observations/recommendations to team!

**Comment by kategarklavs** [comment]
@jackiekazil — Would you like me to replicate this process with @mkhandekar's new sign-in flow? 

In April, I'd distributed (and some team members commented on) this sign-in flow document: https://docs.google.com/a/gsa.gov/document/d/1Z1JmbfSXz1eAucgHCPaOkRwqcAl5PHe5S-C0zJ31tYc/edit?usp=sharing

^^ (This doc is now outdated)

On Friday, I did provide feedback on Meghana's sign-in flow document; happy to keep working on the microcopy!

**Comment by jackiekazil** [comment]
@kategarklavs help me understand -- are you asking if we should do another copy of the feedback cycle on microcopy via google docs OR just use @mkhandekar's doc? (Am I understanding your question correctly?)

**Comment by kategarklavs** [comment]
@jackiekazil Sorry for the belated response — am catching up on email after the design studio. My question was whether I should create a new document (like the one linked above) based on Meghana's new sign-in flow. (I saw that she shared the new version of the flow yesterday.)

@mkhandekar @jackiekazil Would you prefer that I create a new set of recommendations in a Drive doc, or would you like me to continue commenting in Invision?

**Comment by mkhandekar** [comment]
@kategarklavs <https://github.com/kategarklavs> I'm going to continue
commenting on the Invision doc, so no need to make a new drive doc just
yet. Thanks!

**Comment by kategarklavs** [comment]
@mkhandekar Aye aye! In this case, I'll also keep commenting on the Invision doc :)

**Comment by jackiekazil** [comment]
:+1:

**Comment by kategarklavs** [comment]
I've been commenting in InVision on an as-needed basis — closing this issue, for now. (Feel free to reopen, if necessary!)

**Comment by mkhandekar** [comment]
@kategarklavs - sounds good!
