### ISSUE TITLE
Auth screen: editing permissions

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#608]
#### Sprint 22's [Midas + MyUSA in-house usability tests](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-results.md#myusa-auth-screen-editing-permissions) tell us that:
* Participants were not able to edit data without prompting
  * None of the participants realized at first that they could control what data is being shared
  * Many participants did not realize that the "headlines" are collapsed sections
  * Assumption of no important functionality inside the collapsed sections
  * Once collapsed sections were open, participants didn't realize they could uncheck the boxes
* Participants are uncertain what access they are granting
  * What data will be shared?
  * What will MyUSA do with that data?
* Seeing permissions can be reassuring

**Current permissions screen:**
![screen_shot_2015-03-25_at_4 20 31_pm](https://cloud.githubusercontent.com/assets/1598889/7029345/fdcfcc5e-dd2a-11e4-8b10-4eb030ddcddb.png)

#### Goals for a new permissions screen:
* increase clarity around:
  * what can & cannot be edited
  * what can visitors share
  * and how will what they share benefit them
* ensure that visitors slow down to read and understand what this screen asks of them
* reassure that these settings can be changed at any time

**To do:**
- [x] feedback rounds on content 
  - [x] [v1](https://docs.google.com/a/gsa.gov/document/d/1o8oqb3dGmGSbe7wT1Ii1evTI4z7YX5VEqeFPsqA4FIM/edit)
  - [x] [v2](https://docs.google.com/a/gsa.gov/document/d/1EjilMOSzt7U7YHCkg5etWwJ1RMTXdTY7zFcUY9Sjj0s/edit)
- [x] round 1 permissions exploration
- [x] UI elements exploration (check boxes, toggles, form elements)
- [x] share w/ design crit group
- [x] round 2 permissions 
- [x] test the permissions screens as part of [hallway testing in SFFB](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint25_hallway-SFFB.md)
- [x] content v3
- [x] round 3 permissions from testing results

**Comment by mkhandekar** [comment]
[Round 1 of permissions exploration (on Invision)](http://invis.io/952M9GUHA)

Option 3 of 6:
![myusa - permissions - 2](https://cloud.githubusercontent.com/assets/1598889/7028778/262a9f6c-dd26-11e4-90a9-7f37f29cf935.png)

**Comment by mkhandekar** [comment]
We did a round of hallway testing on the following two options: 

#### Explanation First
Makes the reasons for the request more visible
[Round 1 of permissions exploration & usability test (on Invision with annotations & results)](http://invis.io/JY2OTKPPM)
![1per_desc_email firstnamechked](https://cloud.githubusercontent.com/assets/1598889/7182612/8c25d114-e420-11e4-9733-5a4b50eb4f7b.png)

#### Decision First
Makes the controls for sharing information more visible
[Round 1 of permissions exploration & usability test (on Invision with annotations & results)](http://invis.io/T22Q0Q57E)
![3per_toggles_email firstnameyes](https://cloud.githubusercontent.com/assets/1598889/7182674/f2b26960-e420-11e4-9b1c-f039f5f08409.png)
Help text visible:
![3per_toggles_help](https://cloud.githubusercontent.com/assets/1598889/7182675/f70f766a-e420-11e4-9518-28c274c9a582.png)

#### Results
* Full hallway testing results can be reviewed here: [Sign in flow: Hallway testing](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint25_hallway-SFFB.md). 
* A summary of participants reactions broken down by gut reactions, problems encountered and questions asked are on Murally: [Sprint 25 - Permissions screen](https://mural.ly/t/gsa6/m/gsa6/1428702889147)

Participant Reactions:
![sprint25_participantreactions](https://cloud.githubusercontent.com/assets/1598889/7182975/9342ee4e-e422-11e4-86e0-420f3e88071b.png)

**Comment by mkhandekar** [comment]
@kategarklavs has written [Permission page content v3](https://docs.google.com/a/gsa.gov/document/d/1Q9ngbu2iKceXohWAza1r7maNsF8R277Tpp1XfS94u-s/edit) based on @esgoodman's [research](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint25_hallway-SFFB.md).

**Comment by mkhandekar** [comment]
Did this while I was working on permissions a couple weeks ago, but for @juliaelman as we move into development work. You can find the sketch file in drive: [15-04-28_MyUSA_UIElements.sketch](https://drive.google.com/drive/u/0/#folders/0BwWYNZcEDfwafnBKSTdsMmt1N1JpblRPY2k1RVRFMkFVQ1dFMzBaWTJ3eXJBUWpKVFFHSmc).

![myusa_ui elements](https://cloud.githubusercontent.com/assets/1598889/7376710/98a902ba-edaf-11e4-90d8-ec44ff17ba9a.png)

**Comment by mkhandekar** [comment]
Updated Permissions screens, based on @kategarklavs's [content revisions]( https://docs.google.com/document/d/1Q9ngbu2iKceXohWAza1r7maNsF8R277Tpp1XfS94u-s/edit) based on [hallway testing](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint25_hallway-SFFB.md).
- This direction is a mix of Decision first and Explanation first, as we found that visitors wanted _more specific_ explanations of each item and _reassurance_ that they won't be unnecessary email, and this direction explains and reassures upfront (instead of hiding the help explanations behind a click).
- This direction unfortunately makes the page longer, and we heard from participants that it would be helpful for them to see the Allow button sooner.
- [Round 3 of permissions (on Invision)](http://invis.io/ZU2WP2H6B)
- You can find the Sketch file in drive: [15-05-06_MyUSA_Permissions.sketch](https://drive.google.com/a/gsa.gov/file/d/0B4yIa0Upv1JJc1ZqbS1OZG5Ccms/view?usp=sharing)

Sharing nothing. 
![1_per_toggles_allno](https://cloud.githubusercontent.com/assets/1598889/7518680/66dc1f5e-f4aa-11e4-8e01-36d206ab82c6.png)

Sharing email address. 
![2_per_toggles_emailyes](https://cloud.githubusercontent.com/assets/1598889/7518681/66e1f7f8-f4aa-11e4-898f-92aa16c3f075.png)

Sharing first name. Note that when the visitor types their name, the the text in the form UI changes from "Enter your first name (optional)" to "First Name", and the toggle switches from No to Yes. Assumption here is that if visitors type anything into these fields, their intention is to share that information. I don't want visitors to forget to switch the toggle. We should test this. 
![3_per_toggles_email firstnameyes](https://cloud.githubusercontent.com/assets/1598889/7518683/66e4122c-f4aa-11e4-834b-ea9f948b400c.png)

Sharing last name. Same interaction as above.
![4_per_toggles_email firstnameyes copy](https://cloud.githubusercontent.com/assets/1598889/7518684/66e450ac-f4aa-11e4-9d42-5839fb61a90a.png)

Sharing everything. Same interaction as above.
![5_per_toggles_allyes](https://cloud.githubusercontent.com/assets/1598889/7518682/66e3a9b8-f4aa-11e4-86db-9342991a3b2c.png)

**Comment by juliaelman** [comment]
Thanks for the update @mkhandekar! Changing this to "_develop" and am working on coding this up in this pull request >> https://github.com/18F/myusa/pull/638

**Comment by esgoodman** [comment]
To make the page shorter, could we reduce the amount of small text up top? Here's some relevant design pattern info on [signing in](https://designpatterns.hackpad.com/Signing-in-aVfhGsMS3b2), [help text links](https://designpatterns.hackpad.com/Help-text-XqnDcGgTBKQ).

**Comment by esgoodman** [comment]
@kategarklavs ... I was thinking that we might be able to radically condense the second para or maybe delete it altogether.

**Comment by kategarklavs** [comment]
@esgoodman I'm all in favor of shorter copy blocks. And it does seem somewhat redundant to say "Please review the following info ..." and follow that up with "Share your email" and "Share your name."

In short, I'd be content to delete the second paragraph, so long as no one else feels this change would result in major user confusion.

**Comment by mkhandekar** [comment]
Facebook's example for per-item permissions:
- [Article: how it's going for users and Facebook](http://www.businessinsider.com/facebook-login-updates-for-more-privacy-2015-4)
- [The UI](http://www.adweek.com/socialtimes/wp-content/uploads/sites/2/2014/04/login1.png)
- [Facebook's login testing guide](https://developers.facebook.com/docs/facebook-login/testing-your-login-flow/)

Useful links from gov.uk relating to permissions:
- [Help Text](https://designpatterns.hackpad.com/Help-text-XqnDcGgTBKQ)
- [Progressive disclosure](https://designpatterns.hackpad.com/Progressive-disclosure-mi03xhbZQpu): "This is the technique of hiding content on a page until a user interacts with it in some way."

**Comment by mkhandekar** [comment]
I'll be making a version of the permissions page with all scopes. Here are all the scopes:

![myusascopes](https://cloud.githubusercontent.com/assets/1598889/7706534/fea83bca-fe18-11e4-84ac-320fc35f618d.png)

**Select the API Scopes that your Application will use**

Identify you by your email address
- Email Address

Address you by name
- Title
- First Name
- Middle Name
- Last Name
- Suffix

Know where you live
- Home Address
- Home Address (Line 2)
- City
- State
- Zip Code

Know how to contact you by phone or text message
- Phone Number
- Mobile Number

Find out more about you
- Gender
- Marital Status
- Are you a Parent?
- Are you a Student?
- Are you a Veteran?
- Are you Retired?

Add and remove tasks from your MyUSA account
- Allow the application to add task lists and manage its tasks

Send you notifications via MyUSA
- Allow the application send you notifications via MyUSA

**Comment by mkhandekar** [comment]
Closing this issue as it is in production (#638). 
Continuing permissions page with all scopes here (#657).

**Comment by esgoodman** [comment]
Screenshot of the permissions screen as finally built by @juliaelman ![screenshot of the current build](https://cloud.githubusercontent.com/assets/1598889/7518684/66e450ac-f4aa-11e4-9d42-5839fb61a90a.png)
