### ISSUE TITLE
Where in the authorization process do users need more information about how MyUSA works? 

### ISSUE THREAD

**Issue by polastre** [18F/myusa#61]
In interacting with MyUSA, in some aspects of the application, users may need additional context in order to successfully complete their action or navigation.

In what places do users need such assistance?

**Comment by jackiekazil** [comment]
We don't have any context on this... so we are double iceboxing it --- aka closing.

**Comment by esgoodman** [comment]
[Relevant info](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-results.md#midas--myusa-in-house-usability-tests)
