### ISSUE TITLE
Tell current MyUSA users before External DNS change for "MyUSA Coming Soon"

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#615]
There might be a 24hr period where different parts of the country will still see old CGI my.usa.gov

**Comment by jackiekazil** [comment]
@jgrevich is this something that you can help with?

**Comment by jgrevich** [comment]
Sorry @jackiekazil somehow I missed both the @mention here and on slack. Grr!  I'm working with Alan to get this data from CGI today. Here is the JIRA ticket where we can track the issue: https://cm-jira.usa.gov/browse/XCETTSK-2368

**Comment by jackiekazil** [comment]
@jgrevich no worries. I saw the trail! Thank you for scrubbing in on this. :-)

**Comment by esgoodman** [comment]
This would be a good opportunity to ask for research volunteers. Please talk to me before sending the email so I can insert some copy to that effect.

**Comment by jackiekazil** [comment]
:+1: /cc @adelevie @yozlet

**Comment by kategarklavs** [comment]
Will work with @esgoodman to modify existing copy (by end of sprint).

**Comment by jackiekazil** [comment]
@kategarklavs -- Ty for doing this!

**Comment by kategarklavs** [comment]
@jackiekazil You're most welcome!
