### ISSUE TITLE
Sign In Flow

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#617]
#### Sprint 22's [Midas + MyUSA in-house usability tests](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint22_research-results.md#myusa-auth-screen-editing-permissions) tell us that:
* There were many choices to be made
 * Choice 1: LinkedIn or MyUSA?
    * LinkedIn prompts concern: "is this a networking opportunity", "I don't want LinkedIn to spam me more".
    * But familiarity can breed comfort: "I don't know what MyUSA is, so I'll choose LinkedIn"
 * Choice 2: Google or email?
    * Google prompts privacy concerns: "The Google+ sign caught in my mind. It's a social network. I don't want those worlds [personal Google Plus and a government site] connected"
* Usability confusion:
 * Email/password forms look like they apply to both of the top two options
 * Redundant-looking auth screens

**Current user flow:**
[MyUSA — User flow: notes & microcopy](https://docs.google.com/document/d/1Z1JmbfSXz1eAucgHCPaOkRwqcAl5PHe5S-C0zJ31tYc/edit)

#### Goals for updated user flow:
* increase clarity and speed of sign up (fewer clicks)
* language adjustments that tell visitor exactly where they are in sign up process
* assurance what data is being shared and not shared

**To do:**
- [x] round 1 content evaluation of current flow & microcopy
- [x] round 1 user flow understanding / exploration
- [x] UI elements exploration (progress bar, buttons, text hierarchy)
- [x] round 1 user flow
- [x] round 2 microcopy / content 
- [x] share w/ team
- [x] round 2 user flow 
- [x] share w/ design crit group
- [x] test user flows
- [x] round 3 user flow 
- [x] initial sign in screen diagram  
- [ ] ~~style guide for UI elements~~  
- [x] guide/documentation on interaction design

**Comment by mkhandekar** [comment]
@kategarklavs has written [User flow: notes & microcopy](https://docs.google.com/document/d/1Z1JmbfSXz1eAucgHCPaOkRwqcAl5PHe5S-C0zJ31tYc/edit)

**Comment by mkhandekar** [comment]
Here's draft 1 with comments & questions: **[Sign Up flow on Invision](https://projects.invisionapp.com/share/XZ2OPF8SQ#/screens/72821059/comments)**.

![15-04-13_signupflow1](https://cloud.githubusercontent.com/assets/1598889/7119851/0fbecb08-e1d7-11e4-8ab9-9082b579d1f2.png)

@kategarklavs @esgoodman @yozlet @adelevie @juliaelman @jackiekazil

**Comment by esgoodman** [comment]
There's a bunch of useful [Gov.UK patterns](https://designpatterns.hackpad.com/List-of-design-patterns-0eUk1OdHvql) that could be relevant here.

**Comment by mkhandekar** [comment]
Reading: UK.gov's thoughts on [filling out forms & progress bars](https://designpatterns.hackpad.com/Form-filling-behaviour-aXT1vuzBmFb#:h=People-don't-need-progress-bar).

**Comment by jackiekazil** [comment]
:+1:  That is interesting!

**Comment by mkhandekar** [comment]
Draft 1 of the Register & Sign In flow design is on **[Invision with comments & feedback](http://invis.io/QV2ZZFKR3)**, and a couple of key screens are below. 

#### Begin registration
Draft 1 assumes that MyUSA's core sign in user experience is only with their email address -- no third party IdPs. Based on conversations about [whether to retain external IdPs](https://github.com/18F/myusa-ux/issues/4) in the sign in flow, this direction heightens clarity and simplicity of the sign in flow, both for visitors as well as technically for MyUSA and partners. However, [our current integrators don't want our current flow to change](https://github.com/18F/myusa/issues/564) so the next iteration will include external IdPs -- more discussion needs to happen on this.

![1a_beginregistration](https://cloud.githubusercontent.com/assets/1598889/7714615/ee634fa4-fe4d-11e4-998f-e4f262c2737a.png)

#### Check email
MyUSA sends an email with an access link, and provides a way for visitors to explore MyUSA or [go back to the integrated partner](https://github.com/18F/myusa/issues/648).

![1b_checkemail](https://cloud.githubusercontent.com/assets/1598889/7714610/ee60070e-fe4d-11e4-81c9-befbd9611a23.png)

A MyUSA email with access link. See all other [email notifications](https://docs.google.com/document/d/13ERg8aOIACEYqHWuViZjRTIiiRbhBuOwfmyAbb1zDb0/edit).

![1c_email](https://cloud.githubusercontent.com/assets/1598889/7714611/ee6021bc-fe4d-11e4-996a-5a82aed9083d.png)

#### Give permission
MyUSA asks for permission to obtain & share visitor information with integrating partner. Based on [#608 Permissions](https://github.com/18F/myusa/issues/608) work.

![1d_permissions](https://cloud.githubusercontent.com/assets/1598889/7714612/ee60a952-fe4d-11e4-8cc0-a2fe1dbfd89b.png)

The "why" buttons provide inline descriptions for each piece of information MyUSA / agency asks for. 

![1e_permissionswhys](https://cloud.githubusercontent.com/assets/1598889/7714613/ee60b3a2-fe4d-11e4-927c-6d3d26109f77.png)

**Comment by jackiekazil** [comment]
:+1:

**Comment by mkhandekar** [comment]
Draft 3 of the Make an Account & Sign In flow design is on **[Invision with comments & feedback](http://invis.io/EK3AOT0C7)**, and a couple of key screens are below.

### Goals for user flow:

#### 1) Increased clarity and speed of making an account and signing in.

The new flow reduces choices, and necessary choices are clearly articulated.  

*  **Integration of external IdPs** (Google, LinkedIn, etc)  in the sign in flow.  
  * The team had a discussion about our relationship with external IdPs, and talked to integrators. Integrating external IdPs complicate our user experience, making it a confusing and long-winded process for visitors. [[myusa-ux/#4](https://github.com/18F/myusa-ux/issues/4)]
  * The team decided that the next step would be to only utilize Google as an external IdP and to  de-emphasize this choice. [[#663](https://github.com/18F/myusa/issues/617)]
* **Streamlined language on first screen of sign in flow.** We have come to accept the regular combination of terms (sign up, log in, register, etc), but they lean towards services that require usernames and passwords.
  * “Connect with MyUSA”, “Log In with MyUSA”, “Enter your email address” phrases are same on both screens. “Make an account” and “Use existing account” are only action items and are used in place of register / log in (which are commonly when using a username / password).

![1a_register login](https://cloud.githubusercontent.com/assets/1598889/8195891/075e16f8-1454-11e5-930b-11986f0d2454.png)
  * To reduce cognitive overload for the visitor, invisible, in-the-background behaviors help make MyUSA act in the way the visitor wants. These behaviors are illustrated below:

![myusa_register login_flow](https://cloud.githubusercontent.com/assets/1598889/8195907/2bfe2214-1454-11e5-83c0-b5427ecbb952.png)
#### 2) Visitor knows exactly where they are in making an account and signing in

The new flow informs the visitor of their progress through making an account and signing in. There is new language, tweaked language and UI additions to match the overall UX goals — helpful, encouraging and efficient.

![1b_checkemail](https://cloud.githubusercontent.com/assets/1598889/8195913/377e03e8-1454-11e5-88c0-e444fe5cab23.png)


#### 3) Assurance of what data is being shared and not shared

The new flow's permissions page gives the visitor complete control over their personal data: how much they want to share and with whom. Visitors are also helped along the way: optional and required items are clear, and "why?" labels lead to a modal that explains why MyUSA or the integrator is asking for each item. Finally, if primary or secondary action items (buttons) are descriptive and on the longer side to increase clarity, with contextual explanatory text.

_Interactions for Permissions page **coming next**._

![1d_permissionswhys1_whyselected](https://cloud.githubusercontent.com/assets/1598889/8195924/42d3b756-1454-11e5-8a34-a2c0f9dd4ce2.png)
![1d_permissionswhys2_modal](https://cloud.githubusercontent.com/assets/1598889/8195927/4a402ff6-1454-11e5-91df-32f1669c1ce9.png)

**Comment by esgoodman** [comment]
## Working page at devel as of 06/29

![screenshot of the current build](https://cloud.githubusercontent.com/assets/1598889/7518684/66e450ac-f4aa-11e4-9d42-5839fb61a90a.png)

**Comment by esgoodman** [comment]
Wait! My misunderstanding. ^^^ Above is incorrect. NOT screenshots. Comps.

**Comment by mkhandekar** [comment]
The last remaining item on this issue was to create a style guide for UI elements. This will be wrapped into the style guide for all of the work that's been done for MyUSA so far. Will reference issue # when created.

Closing this issue in favor of #735 (Sign in flow — to code).
