### ISSUE TITLE
Login email doesn't identify itself

### ISSUE THREAD

**Issue by konklone** [18F/myusa#618]
I just went to log into MyUSA for use in Tock, and was surprised that neither the sender nor the subject line said "MyUSA" anywhere in it.

![screenshot from 2015-04-13 17 57 31](https://cloud.githubusercontent.com/assets/4592/7126357/927ef660-e206-11e4-9f16-d968363fa78e.png)

The sender just shows "no-reply", which could be anything. Also, "Authentication instructions" is pretty terse, even cold (since "authentication" isn't the word most people think about when logging in). Not to short-circuit usability testing or anything, I just feel like this could be more friendly, especially since gauging emails for their likelihood of being phishing attempts is so important.

**Comment by adelevie** [comment]
Options: 

option 1) change the 'from' address from 'no-reply' to 'MyUSA'
option 2) add MyUSA to the subject
option 3) a mix of 1 and 2

cc @yozlet @kategarklavs

**Comment by yozlet** [comment]
Try adding a name to the configured email address, to make it something like `MyUSA <no-reply@...>` ?

**Comment by kategarklavs** [comment]
@adelevie I'm also in favor of adding MyUSA to the subject line. What about this?

"Complete your login with MyUSA"

True, the first line of the email lets the user know that they'll need to click the link to finish logging in, but I don't think this redundancy would be overwhelming. What do you all think? (My feeling is that the benefit of including "MyUSA" in the subject line outweighs the tiny bit of redundancy here.)

cc @esgoodman @yozlet

**Comment by adelevie** [comment]
> My feeling is that the benefit of including "MyUSA" in the subject line outweighs the tiny bit of redundancy here.

I strongly agree.

**Comment by konklone** [comment]
Is it easy to include the integrating service? e.g. -- 

> "Complete your login to Tock with MyUSA"

I think this will further improve the recognizability and trustworthiness of the email.

**Comment by adelevie** [comment]
That's a good idea, @konklone. This should be feasible.

Thumbsup from @esgoodman and @kategarklavs et al. and I'll add it.

**Comment by mkhandekar** [comment]
:+1: all the way.

**Comment by mkhandekar** [comment]
Also agreed with @adelevie on this point, in addition to @kategarklavs's subject line change.
> option 1) change the 'from' address from 'no-reply' to 'MyUSA'

**Comment by kategarklavs** [comment]
Howdy, all! @adelevie, you have my :+1: 

@esgoodman — does this work for you?

**Comment by esgoodman** [comment]
Works for me! Let's do it.

**Comment by konklone** [comment]
Just a note that I saw a weird new `*|MC:SUBJECT|*` creep into my email subject from MyUSA today.

![image](https://cloud.githubusercontent.com/assets/4592/8284645/fcb2c3ee-18cb-11e5-82c4-cc6054acb0b8.png)

This is from the `tock.18f.gov` login workflow.

**Comment by jackiekazil** [comment]
Done
