### ISSUE TITLE
Missing icon when authenticating with Google

### ISSUE THREAD

**Issue by ultrasaurus** [18F/myusa#623]
For https://midas.18f.us/

The icon appears to be missing:
![image](https://cloud.githubusercontent.com/assets/41906/7237593/60c63480-e751-11e4-96e9-b885661ec393.png)

Even thought it is configured:
![image](https://cloud.githubusercontent.com/assets/41906/7237604/7024bbae-e751-11e4-97c5-cbe35956e5e3.png)

**Comment by ultrasaurus** [comment]
required for Midas ATO https://github.com/18F/midas/issues/703#issuecomment-94530872

**Comment by ultrasaurus** [comment]
This is reproducible with https://midas-dev.18f.us/

![image](https://cloud.githubusercontent.com/assets/41906/7240437/cc208b0e-e765-11e4-8763-d5fb59aee926.png)

**Comment by jackiekazil** [comment]
@adelevie -- I seemed to have labeled this as working, but I don't believe this has been discussed. Are you working on this or should this be moved to backlog?

**Comment by ultrasaurus** [comment]
@adelevie is this being worked on now?  We're now moving forward with our ATO process, so we would love to get this addressed.

**Comment by mkhandekar** [comment]
@ultrasaurus and/or @adelevie, it seems like that image (url: https://midas.18f.us/images/logo-square.png, redirects to https://openopps.digitalgov.gov/images/logo-square.png). Can you check what's going on with the redirect, and can you replace it with either version of the MyUSA logo below? I'd recommend just the icon since it's a small image.

![myusa_logo_wbg](https://cloud.githubusercontent.com/assets/1598889/7565758/a1686114-f7c0-11e4-86d2-4d24a43ebdcc.png)
![myusa_logonotext_wbg](https://cloud.githubusercontent.com/assets/1598889/7565759/a16e4fd4-f7c0-11e4-9e79-38fac88eb7db.png)

**Comment by ultrasaurus** [comment]
I believe that image is supposed to be the product logo, not the MyUSA logo, so when the user sees the Auth page they know to what they are providing data.

We changed the hostname of Open Opps this past week.  I changed all the URLs in the application edit page on myusa:
![image](https://cloud.githubusercontent.com/assets/41906/7994997/e104bf3e-0ac6-11e5-8b07-6629c8bee321.png)

**Comment by ultrasaurus** [comment]
by the way, that screenshot was on:  https://alpha.my.usa.gov/applications/25/edit

**Comment by mkhandekar** [comment]
"image is supposed to be the product logo" -- of course! Yes. 

@adelevie @yozlet can you help Sarah? I don't have access to the apps to investigate further.

**Comment by jackiekazil** [comment]
Reassigning to jacob --- @adelevie please do a brain dump as needed.

**Comment by harrisj** [comment]
The Consent screen settings for MyUSA in [the Google Developers Console](http://console.developers.google.com) was pointing to a staging URL that was no longer there. Once @yozlet fixed to point to the proper image location like so

![consent_screen_-_myusa](https://cloud.githubusercontent.com/assets/2044/8445864/a5f78778-1f70-11e5-9467-ea5e16045c0d.jpg)

The image then showed up once I disabled MyUSA access for my Google account and tried to log into Midas again via MyUSA and Google

![request_for_permission](https://cloud.githubusercontent.com/assets/2044/8445918/71d61e18-1f71-11e5-8852-f80ea4185b0f.jpg)

This solution does not require any deployments or other code fixes. If it happens again, just check the application settings in Google's application console

**Comment by jackiekazil** [comment]
Ty @harrisj! 
@ultrasaurus can you (or other midas rep do the accept on this?)

**Comment by jackiekazil** [comment]
^^ @dhcole

**Comment by jackiekazil** [comment]
This is complete. @ultrasaurus - if this isn't working for you please reopen.

**Comment by dhcole** [comment]
Thanks @jackiekazil and team myusa. I believe that resolves our issue.
