### ISSUE TITLE
Post Small Biz solicitation to MyUSA Facebook Acct

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#626]
Post Small Biz solicitation to MyUSA Facebook Acct.

Account -- https://www.facebook.com/ProjectMyUSA/
Message -- 
We're redesigning MyUSA to streamline sign-in and simplify application management. We'd love to get your opinions. To participate, email myusa@gsa.gov with “peek” in the subject line and we'll get in touch.

**Comment by jackiekazil** [comment]
Shooting to get get #628 finished first.

**Comment by jackiekazil** [comment]
@kategarklavs -- I can't remember -- were we posting this week or waiting for the name change to FB?

**Comment by kategarklavs** [comment]
I'd be happy to post this week: I believe the name change might take up to 14 days to take effect — @jeanninehunter, is that the case?

Also, @esgoodman — any preference on when we post? In other words, would it be better to get the message out now, or to wait until our fb page reflects our actual name?

**Comment by jackiekazil** [comment]
@kategarklavs did this today! YAY!

**Comment by esgoodman** [comment]
I think we can do it now. The name is close enough.
