### ISSUE TITLE
Figure out social media branding

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#628]
We have multiple accounts that are sending multiple messages. 
https://twitter.com/myusa - 'My.USA.gov' <-- @quepol has this one
https://twitter.com/projectmyusa - 'Project MyUSA' <-- I have this one.
https://twitter.com/ProjectMyGov - <-- I have this one also
https://www.facebook.com/ProjectMyUSA - 'Project My USA' <-- I have this one.

Let's coordinate on branding, images, text, etc.

**Comment by jackiekazil** [comment]
@Kategarklavs -- we doing any image changes for backgrounds or profile image?

**Comment by mkhandekar** [comment]
@kategarklavs @jackiekazil @jeanninehunter:

Here are the updated logo files for social media. You should be able to just drag the image from this page and drop it to your desktop to save. Let me know if you need any other elements!

![myusa_logo_wbg](https://cloud.githubusercontent.com/assets/1598889/7565758/a1686114-f7c0-11e4-86d2-4d24a43ebdcc.png)
![myusa_logonotext_wbg](https://cloud.githubusercontent.com/assets/1598889/7565759/a16e4fd4-f7c0-11e4-9e79-38fac88eb7db.png)

**Comment by jeanninehunter** [comment]
Thanks, @mkhandekar!!  These should work!

**Comment by kategarklavs** [comment]
Quick update on this: Facebook is ready to go, and @jeanninehunter is currently working to wrap up Twitter-related updates. We should be able to close this by the end of this week (or Monday).

**Comment by kategarklavs** [comment]
Howdy! Have the Twitter-related updates been made? cc @jackiekazil

**Comment by jackiekazil** [comment]
This is complete.
