### ISSUE TITLE
Post Small Biz solicitation to MyUSA Twitter Acct

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#629]
Text: 
Coming soon: a redesigned MyUSA! Get a sneak peek and give feedback by emailing myusa@gsa.gov with “peek” in the subject line. @18F #myusa

**Comment by jackiekazil** [comment]
Let's fix #628 first. 
/cc @esgoodman

**Comment by kategarklavs** [comment]
See comment on #628 — Twitter should be ready to go shortly.

cc @jackiekazil @jeanninehunter

**Comment by jackiekazil** [comment]
closing ... reopen later if needed.
