### ISSUE TITLE
Evaluate Learn More page with federal employees

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#630]
@mkhandekar has produced a few directions for the Learn More page. We need to select one direction to develop further. To do that, we'll do about 6 remote interviews with federal employees who match the profile of our agency partner contacts. 

- [x] Schedule interviews (we already have participants lined up)
- [x] Write [research plan](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies.md)
- [x] Write [script](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-script.md)
- [ ] Analyze + write [report](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies.md#results)

**Related to** https://github.com/18F/myusa/issues/523 and https://github.com/18F/myusa/issues/495, https://github.com/18F/myusa/issues/524, https://github.com/18F/myusa/issues/62

**Comment by esgoodman** [comment]
- [ ] need to make Learn More mockup.

**Comment by jackiekazil** [comment]
Update: Liz is almost done w/ the report -- will share google doc w/ team.

**Comment by esgoodman** [comment]
[Summary of findings](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md)

**Comment by jackiekazil** [comment]
:+1:
