### ISSUE TITLE
Create CloudFormation template for Cloud Foundry

### ISSUE THREAD

**Issue by adelevie** [18F/myusa#632]
Use a single Cloudformation template to spin up:

- MySQL (can we switch to PG?)
- Cache (elasticache?)
- ELB

**Comment by yozlet** [comment]
Not switching to PG yet. Let's get moved over to CF first.

**Comment by NoahKunin** [comment]
...do even need a CloudFormation script for this next release on Cloud Foundry?

**Comment by yozlet** [comment]
It's not *needed*, but we have the start of one now (based on https://github.com/18F/cloud-foundry-manifests/blob/master/provisioning/elb.json ) and it's what we're using for staging and production. I'm adding ElastiCache too.

@dlapiduz @ozzyjohnson: Where should we keep & version the CFN template? I'm guessing it should be somewhere private.

**Comment by yozlet** [comment]
This is basically done, except I still don't have a standard place to store it. The CFN template sets up the ELB and ElastiCache but not MySQL (because we should probably keep that manually managed for the moment)

**Comment by yozlet** [comment]
Based on @ozzyjohnson's suggestion, the template now has its own private repo: https://github.com/18F/myusa-cfn
