### ISSUE TITLE
Fix asset precompile on Cloud Foundry

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#636]
Asset precompile is failing because it tries to initialize the Rails app, which tries to access the DB at initialization time, which fails because the buildpack doesn't pass in the DB connection info at compile time.

@dlapiduz identified the specifics of the Rails initialization problem: [`User.rb`](https://github.com/18F/myusa/blob/devel/app/models/user.rb#L3-L39) requires our custom [two-factor extension](https://github.com/18F/myusa/blob/devel/lib/two_factor/model_mixin.rb#L11) which extends `ActiveRecord::Base` at init time. Removing the two-factor references from `User.rb` lets precompilation happen without error, but that's not really an option. (The errors are actually coming from `attr_encrypted`, and removing that *may* be an option since we could move to encrypted RDS instead, and that would honestly be much better than `attr_encrypted` anyway. But it may be too much work, and I'm not certain that removing `attr_encrypted` would actually solve the problem.)

Possible solutions:
1. Do asset precompilation before deployment (in the CI system) and remove it from the buildpack entirely.
2. Tweak the buildpack to enable DB connection during the compile phase.
3. Tweak the buildpack to move the asset precompilation from the compile phase to the run phase.
4. Find a way to remove the DB connection dependency from the app initialization.

**Comment by yozlet** [comment]
Note on solution 2: Heroku used to have a Labs feature called `user env compile` to make user environment variables available to the compile phase, but it doesn't seem to be in the ruby buildpack any more (or if it is, it isn't obvious how to enable it).

**Comment by yozlet** [comment]
Fixed in an easy-but-awful way by simply catching the `NoMethodError` exception. (Thanks, @dlapiduz)

**Comment by NoahKunin** [comment]
@yozlet can you speak a little more about the awfulness?

**Comment by yozlet** [comment]
@NoahKunin: Oops, sorry for the slow response!

Here is the awful code in question: https://github.com/18F/myusa/blob/a2f9371ec7ed86c16b6d3249479ea6e676404834/lib/two_factor/model_mixin.rb#L7-L14

See the comments for cause and fix. After the 4 options listed in the issue description, I went for option 5 (paper over the problem while loudly whistling). In practice this solution is _probably_ the best one for the moment; it's cheating, but unlikely to backfire on us.

The ideal one would be option 4: untangle `attr_encrypted` and make it not depend on the DB for asset precompilation, but that requires more Rails surgery than any of us can stomach right now.

**Comment by monfresh** [comment]
Are you sure your asset precompilation is working? I cloned this repo just now and when I try to precompile the assets locally (after setting the proper env vars), it's failing due to a [known issue with using `validates_acceptance_of` with virtual attributes](https://github.com/rails/rails/issues/11853). If I comment out all `validates_acceptance_of`validations, precompilation works fine, even when I undo the `rescue NoMethodError` you added.

The solution is to add all of the attributes (even non-virtual ones) to `attr_accessor` and make sure that line is placed above the validations:
```ruby
# in app/models/user.rb
attr_accessor :just_created, :auto_approve, :terms_of_service, :two_factor_required
validates_acceptance_of :terms_of_service
...
```
```ruby
# in lib/doorkeeper_patches/models/application.rb
attr_accessor :terms_of_service_accepted
validates_acceptance_of :terms_of_service_accepted,
...
```

To test asset precompilation locally, I didn't run `rake db:setup` on purpose so that I wouldn't have a DB and so any code that attempted to connect to the DB would result in an exception. I then ran `rake assets:precompile RAILS_ENV=production`.

For a more generic test that works whether or not you already have the DB created, you can test by specifying a nonexistent DB, like this:
```
env -i GEM_PATH=$GEM_PATH \
       PATH=$PATH \
       RAILS_ENV=production\
       DATABASE_URL=mysql2://user:pass@127.0.0.1/does_not_exist_dbname \
       /bin/sh -c 'bundle exec rake --trace  assets:precompile'
```

**Comment by yozlet** [comment]
Wow, thanks @monfresh, I hadn't realised that was the problem. I'll give that a go.

**Comment by yozlet** [comment]
Initial investigation suggests that the problem is a slightly different (but related) one - the fields in the validations are real, not virtual.

The compilation problem _is_ fixed by adding `attr_accessor` declarations, but since the fields in question are real DB fields, it has the unfortunate side-effect of clobbering some of the ways of setting those values. This may only affect tests rather than real usage but I'm not sure, and I'd rather not risk it until we have a better understanding of what's happening here.

**Comment by monfresh** [comment]
Agreed. It was premature of me to suggest using `attr_accessor` for real fields as well. According to the comments in the Rails issue I linked to, this Rails bug only happens with virtual fields, so there must be something else that is affecting real fields.

However, taking a step back, I would question whether `validates_acceptance_of` is really needed and/or whether a database column is really needed. That validation is meant to be used to make sure that users check a particular checkbox on a form, such as accepting terms of service. If all users must accept the terms of service, then there is no need to create a database column for that attribute. Rails takes care of it for you as a virtual attribute.

I also noticed that you have 2 similar validations related to terms of service, one in the [User model that uses the virtual `terms_of_service` attribute](https://github.com/18F/myusa/blob/devel/app/models/user.rb#L26), and one in the [Doorkeeper Application model](https://github.com/18F/myusa/blob/devel/lib/doorkeeper_patches/models/application.rb#L14-L17) that uses the database column `terms_of_service_accepted`. Is there a reason for having both of these?

You also have another acceptance validation for the database column `two_factor_required`. How is this used from a user perspective? Does the user get to decide whether or not their two factor is required? Could you describe to me what is being validated here? Perhaps I can point you to a better validation method.
