### ISSUE TITLE
Tabindex for field entry on sharing data

### ISSUE THREAD

**Issue by konklone** [18F/myusa#637]
Tabbing from the First Name field took me to the checkbox, instead of to the Last Name field.

![screenshot from 2015-05-05 11 36 02](https://cloud.githubusercontent.com/assets/4592/7476349/f90bb11e-f31a-11e4-9ac5-2c4dda039782.png)

I think the fields should tab naturally from one editable field to the next.

**Comment by adelevie** [comment]
This will be fixed in https://github.com/18F/myusa/pull/638.

**Comment by nickbristow** [comment]
@konklone The tab order you're seeing is correct in terms of how the form is laid out. Top-Down, Left-Right. If the form inputs were re-ordered it may be easier for the user.

**Comment by adelevie** [comment]
@konklone closing this in light of @nickbristow's comment. Feel free to re-open or discuss if you think we need to.

**Comment by konklone** [comment]
I do think we need to discuss this. I think if the tabindex shouldn't be modified away from the form order, then the form order should be modified to make a clear jump from first name to last name. This is how most forms on the internet work that accept a first name and a last name, and the fact that we have the ability to submit that field or not is an implementation detail that shouldn't get in the way of replicating that level of usability.

**Comment by adelevie** [comment]
The fields do still get submitted even if the checkbox is unchecked. If unchecked but still filled out, the value is sent to MyUSA to become part of your profile information. The checkbox is a user's option to share that profile data with the 3rd party application.

**Comment by konklone** [comment]
Got it -- my misunderstanding of the functioning of the checkboxes not withstanding, it doesn't change my point above.

**Comment by adelevie** [comment]
Is there something written down about this expectation to always jump from first name to last name?

The UX for much of MyUSA is fairly complex (e.g. communicating to users what info is shared with whom) and @esgoodman, @mkhandekar, and others on the team are working hard at figuring out designs that reduce that complexity as much as possible. This is one of several (sometimes competing) values we're trying to uphold:

1. effectively communicate to the user how their info is being used (and how they can determine this)
2. accessibility
3. the expectation that tabbing should go from first name to last name 

I'm not arguing against redesigning the forms around number 3 on that list, just providing a reason why the folks on our team could very justifiably opt against it.

**Comment by konklone** [comment]
I'm not saying tabindexes are more important than accessibility or form layout. However, I didn't originally think they would be in tension, and assumed that tab indexes could be adjusted differently than the order laid out on the form.

If that's not desired, or inhibits accessibility, then my request is simply to evaluate manual tabbing as possibly something to optimize for in the overall form design. The evaluation could be already over, and could be to move on, in which case please do re-close it. :) I re-opened because it didn't feel like an evaluation, even an informal one, had occurred.

**Comment by adelevie** [comment]
It's all good :)

At least for now these values do seem to be in tension.

We're also in the middle of some redesigns of that page (in this branch https://github.com/18F/myusa/tree/feature/permissions_page_redesign), so maybe some new issues related to that page will come up. Also, I think our UX folks are now at least aware of the preference/expectation for tabindexes you mentioned, and that can be a factor in ongoing design considerations.

Gonna close this one again. Goodbye, #637, you will be missed.

**Comment by konklone** [comment]
:+1:
