### ISSUE TITLE
Migrate to Cloud Foundry for ATO

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#639]
Move our primary deployment from the current mixture of AWS, CloudFormation, Chef, Shipper, twigs and spit to the shimmering crystal future of Cloud Foundry (plus CloudFormation, but with less spit).

- [x] Fix asset precompilation issue (#636)
- [x] Force HTTPS
- [x] Use [Unicorn](https://github.com/dlapiduz/fugacious/blob/master/Procfile) instead of WEBrick
- [x] Enable New Relic monitoring
- [x] Separate staging and production spaces (#625)
- [x] Configure Google login apps with new URLs
- [x] Document CF setup & deployment (approval forthcoming from @NoahKunin)

**Comment by jackiekazil** [comment]
related #654

**Comment by NoahKunin** [comment]
Seems like there should be some updates here.

**Comment by NoahKunin** [comment]
Per Slack, Team MyUSA is going to re-sort these into `now` vs `later`.

**Comment by jackiekazil** [comment]
:+1:

**Comment by jackiekazil** [comment]
@yozlet  With the closing of #625, does this mean this is all done also?

**Comment by jackiekazil** [comment]
Yes..... yes..... we will close this.
