### ISSUE TITLE
User needs to know why we're asking them information

### ISSUE THREAD

**Issue by polastre** [18F/myusa#64]
When approving an application, user needs to know why they're being asked this information (or additional information) and what we do with the information.

**Comment by jackiekazil** [comment]
@esgoodman is this intended to be closed and that is why it is moved to accept?

**Comment by esgoodman** [comment]
Yes. While that user story is still relevant, we are no longer using Github
to store stories of this kind. Moreover research suggests that people don't
need to know so much as able to find answers when they want them.  so this
user story might need a little rewriting anyway.

**Comment by esgoodman** [comment]
however, it is absolutely your call.

**Comment by jackiekazil** [comment]
Let's close. :-)
