### ISSUE TITLE
"You're almost there" page should use different formatting for email address

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#647]
At present, display of the user's email address on the "You're Almost There" page (i.e. after they've entered their email address to authenticate) is formatted the same as the rest of the body text. We should probably make it stand out in a monospace font, or something.

**Comment by esgoodman** [comment]
@mkhandekar Can you suggest a change? I'd argue that the address should be **bold** to make people more likely to notice if they have perhaps entered it wrong...but maybe you have a better idea?

**Comment by mkhandekar** [comment]
**Email bolded**
Bold seems to be effective and the simplest & fastest thing to implement in the current screen. I'm working on the sign in flow which includes this screen and will make sure that I address the email address in that screen similarly. 
![screen shot 2015-05-14 at 1 24 13 pm](https://cloud.githubusercontent.com/assets/1598889/7637576/ed433ff4-fa3c-11e4-86f3-7e3602bead94.png)

**Another option: with added background color to differentiate even more.**
![screen shot 2015-05-14 at 1 26 38 pm](https://cloud.githubusercontent.com/assets/1598889/7637577/ed45a280-fa3c-11e4-89e8-ec8873d26ccf.png)

**Comment by esgoodman** [comment]
I'd go with the bold. The blue seems a little button-y.

**Comment by mkhandekar** [comment]
:+1:

**Comment by mkhandekar** [comment]
From the [latest sign in work (#736)](https://github.com/18F/myusa/issues/736):

![](https://cloud.githubusercontent.com/assets/1598889/8945446/0c2aa5c4-354d-11e5-8a95-79109e71524d.png)
