### ISSUE TITLE
Should we provide a way for the user to abort sign in flow?

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#648]
Suppose a user goes to Benefits.gov, sees the encouragement to sign in with MyUSA and tries it. In the middle of the flow, due to problems with email or whatever, they decide to give up on signing in and just use Benefits.gov without signing in.

At present, the only way for them to do this is to try to navigate back to where they were before clicking the "Sign In" button. Although OAuth _does_ have a process for dealing with login failure (i.e. return them to the "return to" URL on the app, with a parameter showing failure, and let the app decide what to do) we don't give the user the option to do that.

**Comment by esgoodman** [comment]
cc @mkhandekar -- This does seem like a big flow problem....do something like this: !(https://projects.invisionapp.com/d/main#/console/2318574/72821059/comments/35016801)

**Comment by mkhandekar** [comment]
@yozlet Thanks for bringing this up. Can you speak more about the bolded part? Does that mean, that MyUSA (we) get notified that someone started the sign in process, and then quit it?
> Although OAuth does have a process for dealing with login failure (i.e. return them to the "return to" URL on the app, **with a parameter showing failure**, and let the app decide what to do) we don't give the user the option to do that.

What kind of things can the "app (partner agencies, right?) decide to do" when there is a sign in failure?

cc @esgoodman

**Comment by yozlet** [comment]
@mkhandekar: We should definitely measure when people quit out early (to the extent that we can), but the main purpose is to end up back at the app with an indicator that no, the app hasn't been given identity/authorisation.

The possible reasons for the user explicitly quitting the auth process include being unable to authenticate (no email access right now) or wanting to continue to use the app without handing over identity details or authorisation.

At this point it's up to the app to decide what they can still offer the user. This could range from just continuing to offer the same service but without personalisation (this would apply to Benefits & BusinessUSA) all the way to refusing to let the user go any further (when authentication is explicitly needed for the rest of the flow). In the latter case, it'd be good to follow the example of `gov.uk/verify` and describe alternative routes the user can take to get to their desired outcome.

**Comment by esgoodman** [comment]
I added a sketch to a comment in the Invision site map page that I thought
might address this -- thought I sent it to @mkhandekar but maybe Invision
fooled me on that...

**Comment by mkhandekar** [comment]
@yozlet Thanks for going into detail on this. Agreed on all of it. I wish we could (or can we?) influence some of the messaging on the Agency website if a visitor has quit the sign in process, to tell them that:
> that no, the app hasn't been given identity/authorisation.

@esgoodman I didn't see the sketch until just now when I poked around the Invision, apologies! We are on the same page -- this is addressed on these two screens:
- [step 1: register with email](https://projects.invisionapp.com/share/QV2ZZFKR3#/screens/78398199/comments)
- [step 2: check your email](https://projects.invisionapp.com/share/QV2ZZFKR3#/screens/78398199/comments)

**Comment by mkhandekar** [comment]
We are implementing a ways for visitors to cancel/pause sign in flow throughout the process. Closing this issue.
