### ISSUE TITLE
Do users trust MyUSA as an authentic government service

### ISSUE THREAD

**Issue by polastre** [18F/myusa#65]
User needs to know why they can trust MyUSA / why this is the authentic MyUSA.

**Comment by esgoodman** [comment]
Answered for pre-re-inception version of MyUSA by [walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#do-users-trust-myusa-as-an-authentic-government-service-65). Members of the public might differ, but my assumption (note, it's an assumption) is that government employees would have more experience with government websites and thus would be more picky about what they accept as an authentic government website.

**Comment by jackiekazil** [comment]
Works.
