### ISSUE TITLE
Can't login to MyUSA

### ISSUE THREAD

**Issue by seanherron** [18F/myusa#653]
Upon trying to authenticate:

```
502 Bad Gateway: Registered endpoint failed to handle the request.
```

URL: `https://myusa.18f.gov/users/auth/google_oauth2/callback?state=`
(token stripped out)

**Comment by jackiekazil** [comment]
Just had the same issue. I tried again and it went through. (But still an issue)

**Comment by yozlet** [comment]
This was, I believe, a Cloud Foundry problem with missing workers. @dlapiduz was working on fixing it - any update?

**Comment by dlapiduz** [comment]
@yozlet there was a networking problem but I am not 100% sure that it was the issue... is this fixed now?

**Comment by jackiekazil** [comment]
@dlapiduz, last time @yozlet and I chatted, it wasn't an issue anymore. 
@seanherron, can you confirm that this isn't an issue anymore to your knowledge? 
(Maybe we close this and reopen/reference if it comes up again since we might not be able to replicate?)

**Comment by seanherron** [comment]
@jackiekazil yes, I think it can be closed. I haven't been able to replicate recently.

**Comment by jackiekazil** [comment]
Ty @seanherron!
