### ISSUE TITLE
All the things: ATO related

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#654]
This ticket has all things that are related to the ATO.

**Comment by NoahKunin** [comment]
Just for reference, the master issue is at https://github.com/18F/DevOps/issues/5

**Comment by jackiekazil** [comment]
:+1:

**Comment by NoahKunin** [comment]
Tracking through dependencies This is just ultimately a pointer to https://github.com/18F/myusa/issues/625 at this point, so closing for clarity.
