### ISSUE TITLE
Auth screen: editing permissions (with all scopes)

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#657]
Core interactions for permissions was worked out in #608. Now we are designing the permissions page with all the scopes, to:  
- confirm that those interactions work on different types of content
- keep moving work towards a BusinessUSA partnership

**To dos:**
- [x] draft 1 with all scopes 
- [ ] collaborate with @kategarklavs on descriptions*
- [ ] draft 2, tighten up
- [ ] test
- [ ] adjustments based on tests

*Content note: [Here is the current content for all scopes](https://github.com/18F/myusa/blob/devel/config/locales/en.yml). They'll be the starting point to the design this page, and it will all need to be restructured in the design as well as in this yml file (@adelevie).

**Comment by kategarklavs** [comment]
@mkhandekar Sounds good!

**Comment by esgoodman** [comment]
# Current status

You can leave comments here or in [Invision](https://projects.invisionapp.com/d/#/console/2318574/84696326/preview)

![image](https://cloud.githubusercontent.com/assets/10067318/8242479/6bd4ca8e-15c4-11e5-8924-7bc7360d7c7c.png)

**Comment by esgoodman** [comment]
Note: this has some changes from the previous version -- they are experimental only, just meant to test ideas. Not necessarily to be implemented.

**Comment by esgoodman** [comment]
Folding this into #698. Any structural revisions are iceboxed until we complete a first round of code on every other touchpoint.

**Comment by mkhandekar** [comment]
Closing this & following up adjustments/changes in #698.
