### ISSUE TITLE
Decide what 2FA options MyUSA should offer users and integrators

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#658]
Two-factor authentication is implemented and functional. However, we have a number of UX questions about where and how it shows up. 

* 2FA authentication prompts appear inconsistently in [the existing flow](http://invis.io/7M31O0KF8). 
* The requirement (or lack thereof) is a [concern](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md#security-measures) for some integrators at security-conscious organizations
* 2FA is a UX challenge for speedy and lightweight sign-in, as demonstrated by related issues: #408, #478, #574, #581

The options up for discussion are:
1. Require 2FA of all users of MyUSA, all the time. As a consequence, a 2FA chooser goes into the first-time sign-up and returning user flows. We keep and revise the existing 2FA elements in the account management site. 
2. Strongly recommend mandatory 2FA for some but not all applications. As a consequence, we add a 2FA requirement checkbox to the application creation panel. That in turn adds a 2FA chooser into the first-time sign-up and the returning user flows _only_ for websites that enable mandatory 2FA.   
3. Make 2FA a user-selected, non-mandatory setting. This is the current status quo. When 2FA is enabled, a 2FA chooser pops up during first-time sign-up and returning user flows _only_ for users who have enabled it in the account management site. 
4. Remove access to the 2FA functionality entirely. 

Assumptions: most 18F-ers and other federal employees using MyUSA more than once a month will go through Google OAuth or through secure gov’t email. Based on pretty reliable data, we think that non-federal employees who make a MyUSA account will use the account once or twice a year.

**Comment by esgoodman** [comment]
We asked the cybersecurity channel for their thoughts. The results: NO on (1) and (4), YES PLEASE to (2) and (3). (2) and (3) are compatible, with (2) layering features onto (3). 

@dhcole added some nuance:

> +1: 2factor is super important and app devs might want to leverage it, -1: yes, but myusa is just delegating authorization to another service (google oauth or email + link verification) and 2-factor should happen there

**Comment by esgoodman** [comment]
@adelevie and @yoz, how hard would it be to make 2FA mandatory for some integrations but not others?

**Comment by jackiekazil** [comment]
:+1:

**Comment by mkhandekar** [comment]
Looking at [Google's 2-step verification guide](https://www.google.com/landing/2step) as inspiration as we start to do ours. 

![1a](https://cloud.githubusercontent.com/assets/1598889/7917171/507a94f6-0856-11e5-99c7-f3cce9cd6630.png)
===
![1b](https://cloud.githubusercontent.com/assets/1598889/7917170/507a949c-0856-11e5-90e8-7a4b2a2c18d8.png)
===
![2](https://cloud.githubusercontent.com/assets/1598889/7917168/5079249a-0856-11e5-95c7-71a5ef640922.png)
===
![3](https://cloud.githubusercontent.com/assets/1598889/7917172/507ca052-0856-11e5-99bf-40e494659ef4.png)
===
![4](https://cloud.githubusercontent.com/assets/1598889/7917173/507d5d3a-0856-11e5-88ee-2ad3bd4b6f16.png)
===

Have you seen any other examples for 2FA verification that does a nice job of educating visitors step by step? cc: @yozlet @adelevie @esgoodman @juliaelman @jackiekazil @harrisj

**Comment by esgoodman** [comment]
I feel like Google's flow may be more elaborate than we need. There's a mural.ly doc where I've been collecting examples: https://mural.ly/t/gsa6/m/gsa6/1426803022441.

**Comment by esgoodman** [comment]
Closing because we've decided this and are now implementing the decision.
