### ISSUE TITLE
Interview more stakeholders at partner agencies

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#665]
## Background 

Interviews during Sprint 30-31 with our partners [about the landing page](https://projects.invisionapp.com/d/main#/console/2318574/76846642/preview) revealed [some unexpected complexity](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md). We realized that people from different professional roles interpreted the landing page quite differently. 

## What we're doing

We're now seeking out a wider array of stakeholders in various agencies for 45 minute interviews that:

1. establish a timeline of their encounters with MyUSA, focusing on tools and painpoints

2. continue evaluating (though with much less detail) the landing page so that we map specific informational needs to specific stakeholder roles and points in the process

## Outcomes

This is a further exploration of partner agencies' needs for information (#523) and support (#495) that will lead to an integrator journey map (#651), which itself will help us better support the process of integration (#640).

## Resources
[Script](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-script.md)

Journey maps in Mural.ly #myusa 

[Interview notes](https://drive.google.com/a/gsa.gov/folderview?id=0BzFFCJBPamdCfkV4UDdhYmdiazNUQlJxRUFJNFhQaThlYzAwWklqbDRYWVB6S0FoVnF1bmM&usp=sharing)

**Comment by esgoodman** [comment]
cc @mkhandekar and @kategarklavs

**Comment by esgoodman** [comment]
@mkhandekar I feel like we've completed this task and have built the learnings into a [new landing page](https://projects.invisionapp.com/d/#/console/2318574/82558831/preview) and more [documentation tasks](https://docs.google.com/a/gsa.gov/document/d/1YD9Ag_l_fIdSoBIM6a0rKrZyPE6jSCd-A-6ugVQUX4c/edit?usp=sharing) (such as #673). If you agree, please close!

**Comment by jackiekazil** [comment]
:+1:
