### ISSUE TITLE
Add CrazyEgg javascript to permissions screen

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#669]
CAP is onboarding a bunch of people next week. It would be great to take this opportunity to get some more quantitative-ish data about how people are reading the site. To do that, we need to paste their code into the permissions screen. I don't know if this is possible by Monday, but it'd be nice. cc @yozlet

**Comment by yozlet** [comment]
Since adding this third-party service may cause security problems and information leakage, @NoahKunin has asked for the risk management assessment which usa.gov may have already done.

**Comment by esgoodman** [comment]
Need to get security assessment for @NoahKunin before moving anywhere on this. I'm working on it.

**Comment by juliaelman** [comment]
@esgoodman we can close this one, right?

**Comment by esgoodman** [comment]
Yes.
