### ISSUE TITLE
Review copy changes to landing/learn more pages

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#670]
Based on the [last round of research](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md) Liz copied and pasted text from a variety of sources, then wrote some new stuff for the new public-facing information page. Someone with content expertise (e.g @kategarklavs and/or @jeanninehunter) should review it before it goes live.  

Most recent mockups in [Invision project](https://projects.invisionapp.com/d/main#/console/2318574/82558831/preview)....but check with me or @mkhandekar before you start so that one of us can make sure you have the absolute most recent version.

**Comment by kategarklavs** [comment]
@esgoodman I am happy to review this copy! In Invision now, and it looks like the most recent screens are from yesterday — once the newest screens are up, I'll start commenting :)

**Comment by kategarklavs** [comment]
@esgoodman and @mkhandekar Just added some notes/suggestions to the new front page designs (which look awesome). Happy to discuss in more detail, too :)

**Comment by esgoodman** [comment]
Changes are made, with a few issues to be resolved by Friday.

**Comment by esgoodman** [comment]
Making a new ticket aimed at coding.
