### ISSUE TITLE
Add list of possible scopes to /developer documentation

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#673]
Integrators want to know upfront what types of information about users does a MyUSA account hold. That also is one of the factors that differentiates us as an LOA1 provider from LOA2+ providers. 

Interviews with early-stage integrators [indicate](https://github.com/18F/myusa-ux/blob/master/research/usability/sprint28_agencies-report.md#some-confusion-about-what-information-we-collect) that our current public-facing documentation doesn't actually answer that question. 

It is on the the registration form for a new application, but not in the public /developer section, which is where interviewees expected to find it. 

cc @kategarklavs and @jeanninehunter

**Comment by kategarklavs** [comment]
@esgoodman A clarification question: Does the type of user info a MyUSA account holds vary by partner agency? (It's entirely possible I'm misunderstanding, but I thought each partner could specify scopes.) 

I'm happy to add a short paragraph (or bulleted list) describing the types of information common to all accounts — Liz, going to ping you re: timeline.

**Comment by esgoodman** [comment]
@kategarklavs  -- A bulleted list would work fine. Each partner agency can request different types of data from MyUSA. However, in researching potential sign-on tools partners are looking for information about all the possible types of data they could get via API.

**Comment by esgoodman** [comment]
Subsumed into #688.
