### ISSUE TITLE
Option to force user into connecting with Google 

### ISSUE THREAD

**Issue by afeld** [18F/myusa#676]
The use case:

Communicart is a tool for approval workflows, which for the forseeable future will only be used by GSA employees, who all have Google accounts for work. I've seen users be confused about whether they should "Connect with Google" or type in their email address, though the former is probably easier for them since they would presumably be logged into Google already (on their desktops, at least).

I know there are [open](https://github.com/18F/myusa/issues/617) [questions](https://github.com/18F/myusa/issues/663) around the UX of that page, but wonder if, for this particular case, we can sidestep the problem.

I was initially thinking we could send them directly into the Google auth flow, but I suppose you might need that explainer page saying that, by continuing, they accept the terms of service. Sigh.

Thoughts?

/cc @18F/cap

**Comment by jackiekazil** [comment]
We are making updates to the sign in flow stuff -- those will be coming soon. I am going to close this ticket for now. After the updates are pushed and there is a larger CAP user base, let's chat about again.
