### ISSUE TITLE
[Sec Vuln] Rack and Rails

### ISSUE THREAD

**Issue by maclover7** [18F/myusa#681]
Several Rack/Rails CVEs were announced today. Please make sure you upgrade this app or other apps to be secure.

More info can be found here: https://groups.google.com/forum/#!forum/rubyonrails-security

**Comment by jackiekazil** [comment]
:+1:

**Comment by maclover7** [comment]
Would you like me to submit a PR, or is somebody already working on this?

**Comment by adelevie** [comment]
We're currently assessing which vulns affect us and how to fix each one. That said, if you want to start a PR, that'd be great. Even if we don't merge for some reason, I'm sure it would still be very helpful to us.

**Comment by adelevie** [comment]
in progress: https://github.com/18F/myusa/pull/683

**Comment by yozlet** [comment]
At this point I suspect we should jump straight to 4.2.latest instead. (4.1.12 also just came out, and I believe it still hasn't fixed the polymorphism bug)

**Comment by yozlet** [comment]
So @monfresh fixed this for us in #707 (yay @monfresh!)

We still need to upgrade to Rails 4.2 at some point soon. Opening a separate ticket for that.
