### ISSUE TITLE
Users are unable to create new applications

### ISSUE THREAD

**Issue by harrisj** [18F/myusa#682]
The staging server throws an exception whenever a user attempts to create a new application. The error presented on the page

> Whoops! Check your form for possible errors

suggests the issue is an invalid field in the form. But instead, the issue seems to be an error generating the UID and Secret for the application.

**Comment by adelevie** [comment]
What was that monkeypatch that solved/sidestepped the issue?

**Comment by adelevie** [comment]
Confirmed that this does not affect alpha.my.usa.gov.

**Comment by harrisj** [comment]
Here is the issue clarified. I am not exactly sure how this worked in the past, but the problem is that the Doorkeeper::ApplicationMixin generates [new application IDs and UIDs for a new application with a callback on creation](https://github.com/doorkeeper-gem/doorkeeper/blob/8b59c77ca2324b747ab0570b47f6d14df62fbcc8/lib/doorkeeper/models/application_mixin.rb#L17)

```rails
before_validation :generate_uid, :generate_secret, on: :create

def generate_uid
  self.uid ||= UniqueToken.generate
end

def generate_secret
  self.secret ||= UniqueToken.generate
end
```

The idea is that the code can define a new application by calling `Doorkeeper::Application.new`, setting attributes and on the `save!` it'll generate the secret and the uid. The issue though is that the database schema for `oauth_applications` does not allow those field to be null. So, Rails helpfully sets those fields to the empty string when a new record is created. And the empty string bypasses the `||=` logic that would initialize those fields if they weren't set. So, Rails then tries to save the record and the empty string fields then fail the `validates_presence` requirement for them.

A fix that monkeypatches the `generate_uid` and `generate_secret` methods to also work if the fields are empty strings is forthcoming, but the question remains why this ever worked. It's possible that prior versions of Rails would initialize those fields as nil even if the DB schema didn't allow it and that behavior changed when the Rails version was upgraded.

**Comment by harrisj** [comment]
The issue seems to have been with a particular dump of the database that set those fields to default to the empty string. It still isn't clear why that happened.

**Comment by harrisj** [comment]
Assigning this to @yozlet to match pull request #684

**Comment by harrisj** [comment]
This will also become part of a [future doorkeeper release](https://github.com/doorkeeper-gem/doorkeeper/pull/683)
