### ISSUE TITLE
Decommission MyUSA usage of 18f.us domain

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#687]
This is continuation of #625.

Previous work done: 
- [x] Make sure no one is spinning up new instances that point to 18f.us myusa staging, since that is being decommissioned. 
- [x] Notify points of contact for all staging integrators that a change is on the horizon.
- [x] Notify integrators that they may now update their applications

TODOS:
- [x] Point myusa-staging.18f.gov to the staging ELB
- [x] Track staging integrators' updates
- [x] Pull plug on 18f.us domain when instructed by DevOps.

cc @yozlet @dlapiduz

**Comment by yozlet** [comment]
Done! The myusa-staging CloudFormation stack has been deleted, along with all myusa records in 18f.us (with the exception of myusa-scanee, just in case, but we can delete that soon)
