### ISSUE TITLE
Rake tasks to dump and load the database tables

### ISSUE THREAD

**Issue by harrisj** [18F/myusa#696]
Given some of the recent schema issues identified in #682 and a potential need to rotate the database encryption key, there should be methods to dump a plaintext, **unencrypted** version of the database to load it to a new destination with a possibly different key. Such dumps could also be encrypted and backed up to S3, should we want that as an option. Of course, since this dump will not be encryped, it should be done to a directory that will never be checked into github and cleaned up as soon as possible whenever it is triggered.

Important to-dos

* [x] How does it dump `has_and_belongs_to_many` associations? (**doesn't seem to be needed**)
* [x] Need to write some unit tests
* [x] preserve created_at/updated_at times

**Comment by harrisj** [comment]
Pull request #719 is now ready for review

**Comment by jackiekazil** [comment]
Merged!
