### ISSUE TITLE
Create an accessible, shared working prototype

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#697]
In order to see MyUSA in action, each person now has to set it up locally. That's a lot of duplicated effort, and will probably introduce inconsistencies among different team members' configurations. As part of the prep work this sprint for a big front-end push at the end of the week/next sprint, it would be great to have get a working test app easily accessible to the whole team.

**Comment by esgoodman** [comment]
To clarify: the goal here is to test the sign-in flow, for which we need a test app to sign into. Right now, signing in at staging just routes me to the account management site.

**Comment by juliaelman** [comment]
@esgoodman just talked with @mkhandekar and @harrisj about creating this new instance for testing. we're going to hold off on this work for now, but think it's a great idea for us to implement in the future! :rocket:
