### ISSUE TITLE
Sign In Flow — to code

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#698]
We discussed and iterated through the sign in flow in #617. Here are the screens to be coded for the sign in flow by @juliaelman & @harrisj. **[Sketch files are here](https://drive.google.com/open?id=0B4yIa0Upv1JJdjA0Ni0wQUVmTzA)**.

- [ ] @mkhandekar @esgoodman determines how to best to make integrators aware of style recommendations for login modals.
- [x] @mkhandekar @esgoodman create new layouts for step one of sign in flow, as it is needing more research
- [x] @harrisj adding custom "Why?" text to permissions pages, see #675 [Backlogged]
- [x] @harrisj determines whether new routes need to be created for step by step registration process
- [x] @harrisj figuring out how to display routes in development without need to run separate omniauth client locally
- [ ] @juliaelman styling permissions page with new "Why?" text, modals and text changes.
- [x] @juliaelman adding new header and disclaimer to top page
- [ ] @juliaelman creating new "step by step" styles per the wireframes

# Logging in at Integrator Site

## Prior to arriving at MyUSA
**Choose MyUSA or via email / external IdP**  
![0a_agency_landing_2](https://cloud.githubusercontent.com/assets/1598889/8459809/62ac4aec-1fe5-11e5-9a5f-b810e21de658.png)

**User chooses to log in via email**  
![0b_agency_email](https://cloud.githubusercontent.com/assets/1598889/8459805/62a9ea68-1fe5-11e5-9cef-b4656981f607.png)

## Begin Registration / Log in at MyUSA
**User chooses to log in via MyUSA. These are the log in _and_ make an account screens (these are two different screens, see the following image for interaction)**  
![1a_register login](https://cloud.githubusercontent.com/assets/1598889/8459806/62ab00a6-1fe5-11e5-95f6-59f0d356be4a.png)

**How the log in and make an account screens work**  
![1a_myusa_register login_flow](https://cloud.githubusercontent.com/assets/1598889/8459810/62aeb282-1fe5-11e5-8bda-67b8e338ab1f.png)

## Check email
**User get's a notice saying they need to check their email for the access link**  
![1b_checkemail](https://cloud.githubusercontent.com/assets/1598889/8459807/62abb4e2-1fe5-11e5-9e57-f6ff807e3ace.png)

**User checks their email address, and clicks on Access Link**   
![1c_email](https://cloud.githubusercontent.com/assets/1598889/8459808/62ac1658-1fe5-11e5-9848-49da51e26c00.png)

## Permissions
**User sets permissions**  
This is when none of the toggles are selected "yes".
![1d_permissions_1none](https://cloud.githubusercontent.com/assets/1598889/8459811/62b65ece-1fe5-11e5-8618-698c8dc3e560.png)

This is when one or some of the toggles are selected "yes". Note the explanation text below "Continue Sign In" changes.  
![1d_permissions_2some](https://cloud.githubusercontent.com/assets/1598889/8459812/62ba8878-1fe5-11e5-8691-7cfe279a1dec.png)

"Why?" button hover  
![1d_permissionswhys1_whyselected](https://cloud.githubusercontent.com/assets/1598889/8459813/62bb2846-1fe5-11e5-9e9e-3e32890752e7.png)

User clicks on "Why?" to see explanatory modal  
![1d_permissionswhys2_modal](https://cloud.githubusercontent.com/assets/1598889/8459814/62bc856a-1fe5-11e5-9e3c-98d5d87c9b03.png)

## Logged in
User is logged into integrator website
![1f_loggedin](https://cloud.githubusercontent.com/assets/1598889/8459815/62bce014-1fe5-11e5-9d3d-ebf442e36e83.png)

# Logging in at MyUSA (after logging in at Integrator site first)

**User chooses to log in via MyUSA. These are the log in _and_ make an account screens (these are two different screens, see the above image for interaction)**  
![2a_register login](https://cloud.githubusercontent.com/assets/1598889/8459816/62c44372-1fe5-11e5-8b6f-26b673a06505.png)

## Check email
**User get's a notice saying they need to check their email for the access link**  
![2b_checkemail](https://cloud.githubusercontent.com/assets/1598889/8459817/62c5a9ec-1fe5-11e5-9d62-b3d49bc9acaf.png)

**User checks their email address, and clicks on Access Link**   
![2c_email]
(https://cloud.githubusercontent.com/assets/1598889/8459818/62c86a1a-1fe5-11e5-86f3-6b6911116cae.png)

## Account management 
**At subsequent log ins, user is taken to their dashboard/account management. Permissions page is skipped** (this is account management work. nothing needs to be coded on this screen yet, just want you to know where the access link leads to.)
![2d_profile]
(https://cloud.githubusercontent.com/assets/1598889/8459819/62cc1836-1fe5-11e5-81d1-8b600c709de0.png)

**Comment by harrisj** [comment]
Here's a look at the Routes that currently exist and associated views that would have to be edited:

1. The email signin for MyUSA (not to be confused with email/password signin for application) form is rendered by the `sessions_controller#new` method (part of the Devise gem, **not** in the application). This renders [a login form that allows user to toggle between email or Google signin](https://github.com/18F/myusa/blob/devel/app/views/devise/sessions/new.html.erb)
2. If the user does submit an email for login, that request is sent to `SessionsController#create` which is in the logic for MyUSA (and not a standard part of Devise). This is turn renders out the email and shows the user the [_almost there_ HTML screen](https://github.com/18F/myusa/blob/devel/app/views/devise/sessions/create.html.erb)

All of this stuff exists currently in the application and just needs to be restyled to match the new flow generally. The one exception is whether or not we want a method to check if the user already has registered in 18F with their email previously. This is a backend AJAX method that is specified in the new flow but it may not actually be needed as this flow is a bit confusing and might be redesigned. Waiting until I implement that part.

**Comment by harrisj** [comment]
Just wanted to confirm something with @mkhandekar and @esgoodman. If the user navigates directly to the MyUSA login screen (ie, [alpha.my.usa.gov](https://alpha.my.usa.gov/) after you have logged out), do we want to show them this exact same new layout for the *Log in at MyUSA* and the *almost there/resend email* screens? Or are their important differences for those screens on an application-directed authentication vs. directly logging into MyUSA

**Comment by jackiekazil** [comment]
This ticket will be closed and rewritten by @mkhandekar, so I am assigning back to her. :-)

**Comment by mkhandekar** [comment]
About to put up a new issue capturing all the moving parts of the sign in flow. So, closing this one.
