### ISSUE TITLE
Security issue: jquery-rails and doorkeeper gems are vulnerable due to being out of date

### ISSUE THREAD

**Issue by monfresh** [18F/myusa#705]
I added myusa to our Gemnasium account and it reported 45 out-of-date dependencies, 2 of which are resulting in 10 security alerts: jquery-rails and doorkeeper.

Please update them as soon as you can.

I can also add you to the Gemnasium account so that you can periodically check on the status of the project. Send me an email with the email addresses of the people you would like to give access to.

**Comment by monfresh** [comment]
I just realized that you don't actually need an account to view Gemnasium reports for open source repos. Here is the myusa project page: https://gemnasium.com/18F/myusa

You can also view all 18F public repos here: https://gemnasium.com/18F/

**Comment by harrisj** [comment]
This fix was merged into devel. Will monitor other things that Gemnasium has flagged
