### ISSUE TITLE
Help with troubleshooting an error

### ISSUE THREAD

**Issue by dhcole** [18F/myusa#712]
I seem to be getting this error now when authenticating with a new email address on my "Midas Local" application:

`Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

The URL after the Google account selection screen is: `https://alpha.my.usa.gov/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fapi%2Fauth%2Fcallback%2Fmyusa&scope=profile.email%20profile.first_name%20profile.last_name&client_id=[client_id]`

Not sure if there is something like cached credentials, but I do not see this error when logging in with my @gsa.gov email address. I do get it when logging in with a @gmail.com address.

Can someone help me figure out what's happening? 

cc @harrisj @yozlet

**Comment by harrisj** [comment]
Closing since this specific issue was resolved.

**Comment by dhcole** [comment]
Thanks for your help!
