### ISSUE TITLE
Analyticize MyUSA 

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#720]
Add 18f analytics and DAP to myusa coming soon page & alpha. (For simplicity, we are just going to use one.) These should be added to the bottom of the page. 

### 18F 
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48605964-28', 'auto');
  ga('set', 'anonymizeIp', true);
  ga('set', 'forceSSL', true);
  ga('send', 'pageview');
</script>
```

### DAP
Download [DAP script](https://raw.githubusercontent.com/digital-analytics-program/gov-wide-code/master/Universal-Federated-Analytics-Min.js) & add to repo, then point to local DAP script. (Update the path in the script below. Make sure to maintain the agency & subagency vars.)
```
<script language="javascript" id="_fed_an_ua_tag" src="UniversalFederated-Analytics.1.0.js?agency=GSA&subagency=18F"></script>
```

Let me know if you have any questions. 
For further reading.... 
* 18F Analytics standards: https://github.com/18F/analytics-standards
* DAP: http://www.digitalgov.gov/services/dap/analytics-tool-instructions/

**Comment by esgoodman** [comment]
Yay. Thank you.
